### ISSUE TITLE
Top.outerJoin  output is not as per SQL Outer Join

### ISSUE THREAD

**Issue by rnjtranjan** [composewell/streamly#1032]
>>> Stream.toList $ outerJoin (==) (Stream.fromList [1,2,5,8])  (Stream.fromList [3,1,2])
>>>[(Just 1,Just 1),(Just 2,Just 2),(Just 5,Nothing),(Just 8,Nothing),(Nothing,Just 3),**(Nothing,Just 1),(Nothing,Just 2)**]

The last two elements  (Nothing,Just 1),(Nothing,Just 2) is not required coz it has matched with list1.

**Comment by harendra-kumar** [comment]
This is a known issue and that is why the function is marked as `Unimplemented`. There is this comment to fix it:

>                     lift $ put True
>                    -- XXX Need to use a mutable array
>                    -- when (not used) $ Array.writeIndex i True
>                    return (Just a, Just b1)

Now that we have mutable arrays, we can use that here.
