### ISSUE TITLE
Expose these internal functions

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#1035]
Refer to this PR composewell/streamly-examples#13

## Stream
- [x] Stream.liftInner
- [ ] Stream.evalStateT
- [ ] Stream.timestamped
- [x] Stream.intercalateSuffix
- [ ] Stream.interpose

## Fold
- [x] Fold.rollingHash
- [x] Fold.rollingHashWithSalt

## Unfold
- [ ] Unfold.fold
- [x] Unfold.fromList
- [ ] Unfold.enumerateFromToIntegral
- [ ] Unfold.identity
- [ ] Unfold.outerProduct
- [ ] Unfold.map

## Unicode
- [ ] Unicode.Stream.words
- [ ] Unicode.Stream.lines

## Network.Inet.TCP
- [ ] TCP.writeChunks

**Comment by harendra-kumar** [comment]
The ticked ones are exposed. Others are either not to be exported or cannot be exported as yet because certain things need to be implemented before they can be exposed. See also https://github.com/composewell/streamly-examples/pull/18 .
