### ISSUE TITLE
Parallel composition question

### ISSUE THREAD

**Issue by mryndzionek** [composewell/streamly#107]
I would like to combine two streams in parallel:
 - one doing some periodic thing indefinitely
- second waiting for an asynchronous event, like key press

```hs
toggleLoop `parallel` keyPress
```
I want the combined stream to finish, if the second one finishes. I wasn't able to figure out how to do this, or if it's even possible. Right now this parallel composition seems execute forever.

**Comment by harendra-kumar** [comment]
@mryndzionek you can raise an exception to terminate the stream. See [this example](https://github.com/composewell/streamly/blob/master/examples/AcidRain.hs) which is doing exactly what you cited. Currently there is no `MonadCatch` instance  available, therefore you cannot catch the exception inside stream monad, but you can catch it once you are out of it. Let me know if something like this cannot solve your current issue.

**Comment by mryndzionek** [comment]
Yes, so I think need to catch the exception inside the stream monad. The scenario in my case looks something like:
```hs
restPeriod 10 <> (keyPressed `parallel` getReady) <> restPeriod 5
```
`getReady` is infinite and `keyPressed` finishes immediately after a key press. I was able to come up with something that typechecks, but it doesn't seem to behave properly - the exception is not being caught. Here is a small code snippet (using safe-exceptions):
```hs
train :: MonadAsync m => SerialT m ()
train = do
    e <-  liftIO $ ((tryIO $ return (keyPressed `parallel` getReady)) :: MonadAsync m => IO (Either IOException (SerialT m ())))
    case e of
        Left  _ -> return ()
        Right s -> s

training :: MonadAsync m => SerialT m ()
training = do
    restPeriod 10 <> train <> restPeriod 5
```

**Comment by harendra-kumar** [comment]
@mryndzionek inside tryIO you are using return, therefore constructing an IO action from a pure value. It will not throw any exception. Instead of return you should use runStream to lower the stream into an IO action. 

PS: I am AFK this week so may not be able to respond quickly.

**Comment by mryndzionek** [comment]
Yeah, this was just a quick experiment. I wanted to avoid `runStream` inside stream monad, but if it's the only way, I'll do that. Thanks for all the support.
