### ISSUE TITLE
Elegant way for combining streams

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#110]
I'm using your lib for 1 week now and jeez that's what I was looking for ! Here an example about how I'm combining streams with different signature together : 

```
startHandlers ::  EventStore.Connection -> IO ()
startHandlers eventStoreConnection = do
  runStream $ parallely $ (WorkspaceStream.streamAllInfinitely eventStoreConnection) & S.mapM (\workspacePersisted -> do
    runStream $ serially $ WorkspaceStream.yieldAndSubscribeToWorkspaceUpdates eventStoreConnection workspacePersisted
      & S.mapM (\workspacePersisted -> do
        runStream $ processCommand eventStoreConnection workspacePersisted ))
```

can I express it in a more elegant way ? (removing the call to runStream for example, being able to link an output with an input without writing the mapM as well )...

Thanks !

**Comment by harendra-kumar** [comment]
You can use `mapM_` instead of `mapM` followed by `runStream`. However, the current implementation of `mapM_` is serial, if you want a concurrent implementation then you can define your own like this `mapM_ = runStream . mapM`.

I am not sure what you mean by "being able to link an output with an input without writing the mapM as well".

**Comment by nhenin** [comment]
Let's say you have a Stream A (Input () and output Integer), then a Stream B (Input Integer output String),  in some others libraries like akka stream (scala) or conduit, you can pipe them that way : 
`A | B` **versus**  `A & S.mapM ( \myInteger -> runStream B myInteger )`
then you can have something like that  A | B | C | D really concise

**Comment by harendra-kumar** [comment]
I think you are thinking of joining stream transducers (i.e. stream processing functions). Libraries like conduit join stream transducers together using special operators like `|.`. Stream transducers are of the form `A :: t m () -> t m Integer`, `B :: t m Integer -> t m String`. And you can join those simply like `A & B` in streamly, the way you are expecting. Streamly does not even use a special operator for that it uses the standard `&` or `$`.

However, when you need to transform a stream or stream transducer you need to use a `map` or `mapM`, even a transducer in conduit or pipes or machines libraries would have to use a `mapM` for that. You can try writing your code with conduit (leave aside the concurrency part, just a serial implementation) and it won't be any simpler.

**Comment by nhenin** [comment]
I didn't know that term "stream transducers" but yeah I'm trying to find an abstraction/DSL where I could express flow like a Graph (like in akka stream with the Graph DSL), Machines looks like it, I'll have a look... Thank you for your help !

**Comment by harendra-kumar** [comment]
I took a quick look at https://doc.akka.io/docs/akka/2.5/stream/stream-graphs.html . streamly supports all the fan-in operations i.e. merge, zip and concat. Some flavors of merge are not yet supported but will be supported in future. In the fan-out operations broadcast is achieved using the `foldx` operations and the [foldl](http://hackage.haskell.org/package/foldl) library. Balance and unzip are not yet implemented but are in the roadmap. Let me know if you need more information on any any of the supported operations.
