### ISSUE TITLE
Running strict unicode input benchmarks

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1123]
This benchmark in Streamly/Benchmark/Unicode/Stream.hs:

```
#ifdef DEVBUILD
        -- Requires valid unicode input
        , mkBench "encodeUtf8' . decodeUtf8'" env $ \inh outh ->
            _copyStreamUtf8' inh outh
#endif
```

Requires valid unicode input or it fails.  To automate this, we can:

* Upload a valid unicode input file somewhere and download it when running the benchmark
* To run benchmarks tolerating the failure of this we can either put this under a different flag or handle the exception

**Comment by adithyaov** [comment]
The flag already exists, the following workflow can be used.

To run the unicode benchmarks on valid unicode input, you can do the following,

```
$ Benchmark_FileSystem_Handle_InputFile=<valid-unicode-filepath> bin/bench.sh --benchmarks Unicode.Stream --cabal-build-options "-f include-strict-utf8"
```

Example,

To benchmark using bible from https://bible4u.net/en/download :

```
$ curl https://bible4u.net/static/bible_files/txt/ACV_txt.tar.gz --output ACV_txt.tar.gz
$ tar -xf ACV_txt.tar.gz
$ Benchmark_FileSystem_Handle_InputFile="$(pwd)/ACV.txt" bin/bench.sh --benchmarks Unicode.Stream --cabal-build-options "-f include-strict-utf8"
```

I'm documenting it in `benchmark/README.md`.

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/1450
