### ISSUE TITLE
Track cabal2nix issue for macOS

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1132]
This cabal2nix issue will have to be fixed https://github.com/NixOS/cabal2nix/issues/470 for streamly to be included in nixpkgs. Or we have to find a workaround.

**Comment by sternenseemann** [comment]
streamly is already included in nixpkgs as `haskellPackages.streamly`; proper darwin support will just require an override adding the required frameworks manually in `pkgs/development/haskell-modules/configuration-darwin.nix`.

**Comment by harendra-kumar** [comment]
@adithyaov can you please make changes to `pkgs/development/haskell-modules/configuration-darwin.nix`if needed and send a PR?

**Comment by adithyaov** [comment]
I see  

```
  # streamly depends on Cocoa starting with 0.8.0
  streamly_0_8_1_1 = overrideCabal (drv: {
    libraryFrameworkDepends = [
      darwin.apple_sdk.frameworks.Cocoa
    ] ++ (drv.libraryFrameworkDepends or []);
  }) super.streamly_0_8_1_1;
```

here: https://github.com/NixOS/nixpkgs/blob/5f136de48c925a19478268fe82f8de16ea98a710/pkgs/development/haskell-modules/configuration-darwin.nix#L252

This can be closed I believe?
