### ISSUE TITLE
Avoid exposing nilM, use "before" instead?

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1138]
This issue is only as a note to remember. We have not exposed `nilM` yet.

`before action Stream.nil` can be used in place of `nilM`.

We could express `before` in terms of `nilM` too (`before action xs = nilM action <> xs`) but the advantage of using `before` is that it can fully fuse whenever possible.

**Comment by adithyaov** [comment]
Is there a reason to not use `nilM`?
Too many options lead to confusion. If `before action nil` and `nilM` are exactly the same, we might as well remove `nilM`.

**Comment by adithyaov** [comment]
And remove `nilM` example in `before`.
