### ISSUE TITLE
Ring buffer data structures

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1147]
Make ring buffer a first class streaming citizen by providing read unfold and write fold for it just like array. That will enable us to use ringbuffers more e.g. `lastN` can actually return a ringbuffer instead of array.

**Comment by harendra-kumar** [comment]
PR #1340 added signatures for the ring buffer APIs. Let's implement those.

**Comment by adithyaov** [comment]
This will also require extensive testing.
