### ISSUE TITLE
Add char and numeric parsers

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1199]
We have `Streamly.Internal.Data.Binary.Decode` to decode binary values to Haskell values. On similar lines we can have a `Streamly.Internal.Unicode.Char.Parser` module to decode/parse a char stream to Haskell values. It can be used to parse a text input. We can either supply just the predicates for various parsers or have the parsers as well. To begin with just the predicates should be enough. e.g. we can use `isDigit` predicate for the `digit` parser:

```
digit :: Parser m Char Char
digit = satisfy isDigit
```

Similarly, we can have `letter`, `space` etc. Basically, a parser corresponding to each predicate. Latin` predicates can go in the Unicode.Latin1 module.

Implement `inClass` predicate in Unicode.Char module.

Numeric parsers:

```
decimal :: Integral a => Parser m Char a
```

Similarly, parsers for `hexadecimal`, `signed`, `double`, `rational`, `scientific`. See `Data.Attoparsec.ByteString.Char8`, we need equivalent functionality.

**Comment by adithyaov** [comment]
This is solved/superseded by #1302 and #1290
