### ISSUE TITLE
Monoid law broken with `ExceptT` and parallel composition

### ISSUE THREAD

**Issue by georgefst** [composewell/streamly#1203]
Consider:

```hs
f :: Bool -> IO ()
f b =
    runExceptT (SP.drain stream) >>= \case
        Left () -> putStrLn "error handled"
        Right () -> pure ()
  where
    stream = SP.fromAsync $ if b then s <> mempty else s
      where
        s = SP.fromSerial $ SP.repeatM action
    action = liftIO (putStrLn "error") >> throwError ()
```

Obviously, the `b` argument should be redundant, by the monoid right-identity law. But:

```
Main λ> for_ [False, True] $ \b -> f b >> putStrLn ""
error
error handled

error
*** Exception: thread blocked indefinitely in an MVar operation
```

i.e. with `<> mempty`, the thrown error doesn't get handled.

I *think* this is the root of a practical issue I have with `ExceptT` errors not propagating to bring down the whole stream. Instead, siblings just carry on running.

**Comment by harendra-kumar** [comment]
This looks like a generic issue with concurrent streams rather than a Monoid instance issue. For example, even this fails with the same error:

```
{-# LANGUAGE LambdaCase #-}
import qualified Streamly.Prelude as SP
import Control.Monad.Trans.Except
import Control.Monad.IO.Class

main :: IO ()
main = do
    runExceptT (SP.drain stream) >>= \case
        Left () -> putStrLn "error handled"
        Right () -> pure ()
  where
    stream = SP.fromAsync $ SP.replicateM 1 action
    action = liftIO (putStrLn "error") >> throwE ()
```

Let me take a look what's going on.

**Comment by harendra-kumar** [comment]
`insepctMode` provides debug output in such cases. Ran this to debug:

```haskell
main = do
    runExceptT (SP.drain $ Stream.inspectMode $ Stream.maxThreads 1 stream) >>= \case
        Left () -> putStrLn "Left"
        Right () -> putStrLn "Right"
  where
    stream = SP.fromEffect action `SP.async` Stream.nilM (liftIO $ putStrLn "Done")
    action = liftIO (putStrLn "throwing error") >> throwE ()

```

Got:

```
throwing error
sendWorkerWait: nothing to do BlockedIndefinitelyOnMVar
Creator tid = ThreadId 1
style = AsyncVar
---------CURRENT STATE-----------
outputQueue length computed  = 0
outputQueue length maintained = 0
outputDoorBell = Nothing
needDoorBell = True
running threads = fromList [ThreadId 2]
running thread count = 1
---------STATS-----------
total dispatches = 1
max workers = 1
max outQSize = 0

exceptt: thread blocked indefinitely in an MVar operation
```

It shows we got the `BlockedIndefinitelyOnMVar` exception. There is a running thread (`running thread count = 1`), we are waiting for a doorbell (`needDoorBell = True`), we got no output from the worker thread yet (`max outQSize = 0`).

**Comment by harendra-kumar** [comment]
ExceptT is a stateful monad, we save and restore the state of monad when we run concurrent actions. It may have something to do with that.

**Comment by harendra-kumar** [comment]
This code is clearly wrong for `ExceptT` because ExceptT would short circuit the code:

```
workLoopLIFO q st sv winfo = run

...

                r <- liftIO $ runin $
                        foldStreamShared st yieldk single (return Continue) m
                res <- restoreM r
                case res of
                    Continue -> run
                    Suspend -> stop
```

As we restore the state, the control will return from this worker loop and we won't be sending anything back to the waiting executor. This would work for non-control flow manipulating monads though e.g. StateT.

**Comment by harendra-kumar** [comment]
Stateful monads are not fully supported yet with concurrent streams ([see this note](https://github.com/composewell/streamly/blob/ec99341b49a4111ee4b6e41bf4a7be4ae9154349/docs/monad-transformers.md#using-monad-transformers)) , as concurrent modification of state needs to be handled with correct semantics. Currently independent copies of the state get modified by multiple threads and there is no way to merge back the state changes when the threads are done, also other worker threads won't see the change in state immediately when another thread modifies it.

**Comment by harendra-kumar** [comment]
Also see https://github.com/composewell/streamly/issues/247 .

**Comment by georgefst** [comment]
> This looks like a generic issue with concurrent streams rather than a Monoid instance issue.

Yeah, I suspected so. I went with the `(<> mempty)` example as the simplest way of showing that this is definitely a bug.

> Stateful monads are not fully supported yet with concurrent streams

Fair enough. I'm sure it's not easy to implement! Is it much of a priority? Would be an awesome feature to have.

Otherwise, until such time perhaps the instances which enable this could have a warning attached, similarly to a deprecation notice? We Haskellers tend to assume with this sort of thing that if the types work out, it's probably supported. And that note is not in a place where many people would come across it.

**Comment by harendra-kumar** [comment]
The serial semantics cannot be preserved if we make them concurrent. Though we can define some lax semantics which could still be useful, but then it may be confusing because users will expect the same behavior as serial. We can possibly create new monads with concurrent behavior though.

I was thinking of using a dummy type class constraint to make the compilation fail for such monads. But we can do that only in the next major release.

**Comment by harendra-kumar** [comment]
Targeting this to 0.9.0 to add a constraint so that the broken monads are not allowed with concurrent streams.

**Comment by harendra-kumar** [comment]
We are deprecating the concurrent stream types and using a new explicit concurrency model in 0.9.0, so this issue is obsoleted.

**Comment by georgefst** [comment]
Ooh, wow, sounds like a big change! How usable is the current `master` branch, if I wanted to play around with it before release?

**Comment by harendra-kumar** [comment]
Master branch is fully usable, all tests and benchmarks are working. Old code should continue working except some breaking changes that may require changing code. There is a separate `streamly-core` package now consisting of core functionality having dependencies only on boot libraries (with some exceptions that will be remove in future). The streamly package reexports the streamly-core package plus concurrent streams, networking etc.

There is only one Stream type now which is called `Stream`. Concurrent operations are in the `Streamly.Data.Stream.Concurrent` module. Any feedback on any changes in this release will be greatly appreciated. If there is something critical we will fix that before release.

**Comment by georgefst** [comment]
Cool. No actual changes were necessary for my code to run. As for removing deprecated functions, I'm still stuck with `Streamly.Internal.Data.Stream.IsStream.hoist` and `Streamly.Prelude.drain`, which I can't see how to replace. I'll probably wait until there's documentation on Hackage and a proper migration guide. I'm curious to see how one now switches between different kinds of concurrent streams (`Streamly.Data.Stream.Concurrent.append` seems to be behaving like `asyncly . mconcat`).
