### ISSUE TITLE
Naming of yield and yieldM APIs

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#121]
@mgsloan pointed out that these names are confusing in a monadic composition as other libraries use the same names with different behavior in monadic composition:

> While reading the "Generating Streams" section of the tutorial, I
  expected that `S.toList $ S.yieldM getLine >> S.yieldM getLine`
  would read two lines and yield them, but the resulting list only has
  the second line. This expecation comes from generators in many
  languages using `yield` as a keyword, and also from Conduit's
  monadic composition + yield. I'm not saying that this is wrong, just
  that it's unexpected given the name `yield`.

These are essentially "singleton" stream creation operations. Some alternative names to convey the meaning more precisely are:

* wrap/wrapM - wrap a pure value or a monadic action to create a singleton stream
* single/singleM - create a singleton stream from a pure value or monadic action
* singleton/singletonM - more verbose and tedious to write

Any opinions?

**Comment by mgsloan** [comment]
I think I prefer `single` / `singleM` - shorter than `singleton` and just as clear.  `wrap` to me brings to mind newtype wrapping ala http://hackage.haskell.org/package/lens-4.17/docs/Control-Lens-Wrapped.html

**Comment by harendra-kumar** [comment]
I have not used lenses much so not biased by that. The main difference between `single` and `wrap` is that `single` is a noun conveying the idea of a single element stream whereas `wrap` conveys the process of wrapping a bare action and converting it to stream. That way `wrap` is more like `yield`, `lift` and `return` which are other names for almost the same thing in this case.  Almost all other combinators are verbs, conveying the process of doing something, so that way it sounds better and consistent. However, in favor of `single` many other libraries use `singleton` for the same purpose. But I am not very much opinionated on this, so let me know what you think.

**Comment by mgsloan** [comment]
Hmm, that's a good point about the noun vs verb consistency.  I don't have a strong opinion here, just bikeshedding!  Perhaps it's fine to stick with yield, but explicitly acknowledge in the docs that using yield with the monadic interface does not work the same as conduit / languages with a "yield" keyword for generators.

**Comment by harendra-kumar** [comment]
I guess `yield` is sufficiently controversial to avoid. The replacement verb is `wrap` and noun is `single`. `wrap` too looks good to me, it has similar intuition as `lift` i.e wrapping something into a stream.

**Comment by harendra-kumar** [comment]
I am going with `wrap` and `wrapM`, they avoid the confusion arising from yield/yieldM, are short, and are verbs just like other combinators.

**Comment by harendra-kumar** [comment]
I just realized that we can use `from` and `fromM` for these. It would be consistent with the `fromList`, `fromFoldable` etc terminology that we are consistently using for converting some container to stream.

**Comment by harendra-kumar** [comment]
`fromPure` and `fromEffect` are other alternatives.

**Comment by harendra-kumar** [comment]
We have thought about these from stream perspective, now we have parsers as well and they also have `yield` and `yieldM` primitives. I seem to like using `value` for a pure value and `effect` for a monadic value, they are neutral and equally applicable for streams and parsers.

**Comment by harendra-kumar** [comment]
This has been fixed in 0.8.0.
