### ISSUE TITLE
Add a test for wAsync behavior check

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1224]
WAsync broken behavior was caught by doctests but not by tests. We can add a sanity test to check it:

```
[ 180.79421] error: Stream.toList $ Stream.fromWAsync $ Stream.maxThreads 1 $ stream1 `wAsync` stream2
[ 180.79468] error: in comment at 497:1
expected: [1,4,2,5,3,6]
 but got: [1,2,3,4,5,6]
             ^
```

There are some tests in the WAsync test module but they are commented out.

**Comment by rnjtranjan** [comment]
It's not reproducible. is it a random behavior?

**Comment by harendra-kumar** [comment]
Now it has been fixed, it was during a change that broke the code.
