### ISSUE TITLE
Module organization

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#130]
Keeping in mind the solution proposed in #122, for separating the individual stream type APIs in there own modules we can organize them as follows:

```
-- Pure APIs
* Streamly.Pure
* Streamly.Pure.Parallel

-- monadic streaming APIs
* Streamly.Serial
* Streamly.Async
* Streamly.Ahead
```
The user will have to import one or more of these modules depending on the usage.

Also, if we want to implement non-streaming (i.e. buffering) APIs they can live in the following modules:

```
-- Buffering APIs
* Streamly.Serial.Buffered
* Streamly.Async.Buffered
* Streamly.Ahead.Buffered
```

See https://github.com/composewell/streamly/blob/docs/docs/streamly-vs-lists.md for a background on the classification. See #122 for separating by the concurrency style. Note that in the pure case ordering does not matter and therefore there is only one concurrency style.

**Comment by harendra-kumar** [comment]
Another problem that we have today is that a `MonadAsync` constraint is required for all the monadic combinators even if we are using it for Serial streams. This is because the async operations require this constraint and since we have the same function definition for all types we cannot avoid it for serial versions. With the new scheme since we have separate versions of the combinators we can always avoid using the constraint on serial ones. This allows more monads to be used for those omcbinators e.g. we can even use the Identity monad.

**Comment by harendra-kumar** [comment]
To support lists and strings compatible with the standard lists and strings (see #131), we may need a few more modules:

```
Streamly.List
Streamly.List.Parallel
Streamly.List.Compat
Streamly.String
```

The compat module can house the standard list compatible partial versions of total APIs in streamly.

**Comment by harendra-kumar** [comment]
If we have Streamly.List.Compat then we may need Streamly.String.Compat as well. Alternatively we can create a separate package for compat modules.

**Comment by harendra-kumar** [comment]
This is roughly the module list that I have been contemplating to use going ahead:

```
# Serial stream combinators
Streamly.Stream         
Streamly.Foldl          -- composable left folds
Streamly.Sink           -- special left folds ignoring results (for convenience)
Streamly.List
Streamly.String
Streamly.Array
Streamly.FileIO
Streamly.NetworkIO

# Concurrent stream combinators (currently called ahead)
Streamly.Concurrent.Stream 
Streamly.Concurrent.Foldl
Streamly.Concurrent.Sink

# Async stream combinators
Streamly.Async.Stream
Streamly.Async.Foldl
Streamly.Async.Sink
```

The serial, concurrent and async combinators are kept under their own module name spaces, this reduces the clutter and keeps things clean for the default serial case. Note that we are creating monomorphic combinators for each stream type to make the concurrency explicit and controlled on a combinator basis.

We can still keep the polymorphic combinators in `Streamly.Prelude`. More modules may get added to the above list e.g. `Streamly.Scanl` and `Streamly.Scanr` for composable left and right scans.

Any feedback is welcome.

**Comment by harendra-kumar** [comment]
See also #486 and PR #536 .

**Comment by adithyaov** [comment]
This is obsolete.
