### ISSUE TITLE
A scanMany combinator

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1308]
Like foldMany. The current scan combinator stops if the scanning fold terminates. The proposed `scanMany` would start fresh after terminating.

This combinator can be added to streams/folds/unfolds.

**Comment by rnjtranjan** [comment]
What will be signatures for "scanMany" for Fold and UnFold?

**Comment by harendra-kumar** [comment]
It will be same as scan. The only difference between scan and scanMany is that scanMany continues to scan again after it terminates.

**Comment by harendra-kumar** [comment]
It may be useful to pass a state from one scan instance to the next. For example, when splitting a stream into slices we may have a global state running through all splits and a local state (length of the split) running through a single instance. This can possibly be implemented by using a `Refold` in `scanMany`.

**Comment by harendra-kumar** [comment]
Done.
