### ISSUE TITLE
0.8.1 fails to build on FreeBSD

### ISSUE THREAD

**Issue by hasufell** [composewell/streamly#1365]
Failure:

https://gitlab.haskell.org/haskell/ghcup-hs/-/jobs/874446#L2150

```
Building library for streamly-0.8.1..
src/Streamly/Internal/FileSystem/Event.hs:63:2: error:
     error: "FS Events not supported on this platform"
   |
63 | #error "FS Events not supported on this platform"
   |  ^
#error "FS Events not supported on this platform"
 ^
1 error generated.
src/Streamly/Internal/FileSystem/Event.hs:1:1: error:
    `clang' failed in phase `C pre-processor'. (Exit code: 1)
  |
1 | -- |
  | ^
<<ghc: 939738192 bytes, 259 GCs, 5678004/13308344 avg/max bytes residency (7 samples), 33M in use, 0.001 INIT (0.001 elapsed), 0.394 MUT (1.504 elapsed), 0.188 GC (0.191 elapsed) :ghc>>
```

----

Reason:

https://github.com/composewell/streamly/blob/a0206907dab8cf2d5d339e794bd4d61bba37a634/src/Streamly/Internal/FileSystem/Event.hs#L53-L64

https://github.com/composewell/streamly/commit/3b8932e74c8864ab9e1775a113b830f3a1a2ab98

**Comment by harendra-kumar** [comment]
We can exclude this module in the cabal file when the OS is not linux/darwin/windows. @hasufell would you like to fix it? After the fix we can bump the version to 0.8.0.1 and release it.

Can we add a CI for BSD?

**Comment by hasufell** [comment]
https://github.com/composewell/streamly/pull/1367

> Can we add a CI for BSD?

There is https://github.com/marketplace/actions/freebsd-vm but have no interest right now to play with it. I build my FreeBSD stuff on ghc gitlab.

**Comment by harendra-kumar** [comment]
It seems hackage does not like this change:

```
$ cabal upload streamly-0.8.1.1.tar.gz
hackage.haskell.org username: harendra
hackage.haskell.org password:
Uploading streamly-0.8.1.1.tar.gz...
Error uploading streamly-0.8.1.1.tar.gz: http code 400
Error: Invalid package

Duplicate modules in library: Streamly.Internal.FileSystem.Event
```

**Comment by hasufell** [comment]
> It seems hackage does not like this change:
> 
> ```
> $ cabal upload streamly-0.8.1.1.tar.gz
> hackage.haskell.org username: harendra
> hackage.haskell.org password:
> Uploading streamly-0.8.1.1.tar.gz...
> Error uploading streamly-0.8.1.1.tar.gz: http code 400
> Error: Invalid package
> 
> Duplicate modules in library: Streamly.Internal.FileSystem.Event
> ```

I think we need elifs, because cabal can't know that the platform if conditions are exclusive

**Comment by harendra-kumar** [comment]
Fixed: https://github.com/composewell/streamly/pull/1371
