### ISSUE TITLE
Add a CI for BSD

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#1368]

**Comment by sjakobi** [comment]
FYI, `bytestring` uses Cirrus for this: https://github.com/haskell/bytestring/blob/master/.cirrus.yml

**Comment by harendra-kumar** [comment]
Thanks for the pointer @sjakobi !

**Comment by harendra-kumar** [comment]
From @jkoshy : FYI, re: FreeBSD CI: SourceHut is pro open-source and supports a number of OSes, including some truly obscure ones: https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd.  Cirrus CI also offers FreeBSD builds: https://cirrus-ci.org/guide/FreeBSD/.

**Comment by harendra-kumar** [comment]
Sourcehut (https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd) is another alternative suggested by @jkoshy .

**Comment by adithyaov** [comment]
See: https://github.com/composewell/streamly/pull/2743
