### ISSUE TITLE
Signatures of array APIs

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1403]
In many of the array APIs we are using the array we are operating on as the first parameter. I think it should be the last parameter as in the stream APIs we have stream as the last parameter. Except in snoc style API which follow the `b -> a -> b` style after the left fold.

**Comment by adithyaov** [comment]
How about functions like `asPtr` and `asCString`. It is more convenient for the array to be the first argument?

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/1458
