### ISSUE TITLE
make fold smart constructor naming consistent

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1439]
Maybe a good idea to name the `mkFold*` to make those similar to `foldl'` and `foldlM'`:

Rename `mkFold_` to `foldt'`, this is similar to `foldl'` except that this is a terminating fold hence the `t` suffix:

```
{-# INLINE foldt' #-}
foldt' :: Monad m => (b -> a -> Step b b) -> Step b b -> Fold m a b
foldt' step initial = Fold (\s a -> return $ step s a) (return initial) return
```

Rename `mkFoldM_` to `foldtM'`:

```
{-# INLINE foldtM' #-}
foldtM' :: Monad m => (b -> a -> m (Step b b)) -> m (Step b b) -> Fold m a b
foldtM' step initial = Fold step initial return

```

Remove `mkFold` as could be expressed as (though the Step type is `Step s s` in this but that usually does not matter:

```
mkFold :: Monad m => (s -> a -> Step s s) -> Step s s -> (s -> b) -> Fold m a b
mkFold step initial extract = extract <$> foldt' step initial
```

Remove `mkFoldM` as we can fmap an extract function on `foldtM'`.

**Comment by adithyaov** [comment]
We should not remove `mkFold` and `mkFoldM` as they are sometimes more
convenient. In some cases they reduce the number of possible states that the
user has to define while making folds.

Eg.

1 state.
```
genericIndex :: (Integral i, Monad m) => i -> Fold m a (Maybe a)
genericIndex i = mkFold step (Partial 0) (const Nothing)

    where

    step j a =
        if i == j
        then Done $ Just a
        else Partial (j + 1)
```

VS

2 states.
```
genericIndex :: (Integral i, Monad m) => i -> Fold m a (Maybe a)
genericIndex i = extract <$> foldt' step (Partial 0)

    where

    extract (Left a) = Just a
    extract (Right _) = Nothing

    step j a =
        if i == j
        then Done $ Left a
        else Partial $ Right (j + 1)
```

As a matter of fact, `mkFold` and `mkFoldM` are more useful than `mkFold_` and
`mkFoldM`. In most cases termination can be very direct.
