### ISSUE TITLE
Make the "sum" fold numerically stable

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1440]
We have a numerically stable impl in https://github.com/composewell/streamly-statistics with similar perf.

**Comment by adithyaov** [comment]
Replace the sum in streamly with that of streamly statistics and re-export it from streamly-statics

**Comment by harendra-kumar** [comment]
1. Remove the Data.Fold import from Data.Fold.Window module
2. Use Data.Fold.Window.sum to implement Data.Fold.sum
