### ISSUE TITLE
Mean, variance and stdDev folds

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1441]
These are in streamly package as well as in https://github.com/composewell/streamly-statistics . We should perhaps retire these from streamly and only keep in statistics package.

**Comment by adithyaov** [comment]
Remove these from streamly

**Comment by adithyaov** [comment]
Deprecate variance and stdDev. Keep mean. Report mean from streamly-statics

**Comment by adithyaov** [comment]
Re-export all duplicated API from streamly-statics. Check for implementation.
