### ISSUE TITLE
Remove the `fusion-plugin` CI?

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#1456]
The fusion plugin CI is tested by the regression checking CI. The regression checking CI is not run on master. We can have a separate workflow that only runs the fusion plugin CI on master after the merge.

**Comment by harendra-kumar** [comment]
The only difference is that the fusion-plugin CI runs the tests while benchmark regression does not.

**Comment by harendra-kumar** [comment]
Not going to remove it as we need tests to be run.
