### ISSUE TITLE
Module wise test organization

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#146]
How about having a test file for each user facing module? It will be easier to trace tests for the corresponding source. Plus, the test file can be referenced in the documentation for example usage, if it is organized per module it will be easier for users to find test examples for the APIs.

**Comment by harendra-kumar** [comment]
We can use a single entry point for a test driver for each module. The tests for different functions in the module can be registered in the test driver. The driver can even have an implicit name based on the module name e.g. `module_test`.

This way we do not have to export the internal functions for testing purposes. The exports, imports and the test driver code could be under a CPP conditional.

The test driver to test all these modules can be generated automatically from the cabal file. Initially we can do it manually. We just need to import a module and call its test driver. We should try to test the lowest level modules first and then move up in the hierarchy. This could also be automatically inferred from the dependencies among modules. In fact, the test driver of a higher level module should first test all its dependencies if not already tested.

**Comment by pranaysashank** [comment]
We currently expose most of the modules through the Internal hierarchy which should make testing much easier.

@adithyaov You were interested in this.

**Comment by adithyaov** [comment]
@harendra-kumar @pranaysashank I'll work on this after working on `additional-combinators` and `streamly-*` packages.

For the tests that are already available, this should be an easy copy and paste :-).

PS: Weirdly enough, I did not get a notification when I was mentioned.
