### ISSUE TITLE
Implement a stream tapping API

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#147]
#103  discusses a tracing API to print what is going through the stream without changing the stream. However, that is just a specific tracing use case. In general, we may want more powerful tracing mechanisms e.g. trace a particular interesting part of the stream or do something when we observe something passing through the stream, e.g. log it to a file or trigger some action.

I propose a monadic `tap` API for achieving this in general. A tap would just tap the stream at that point, cloning it for side effects without changing the original stream. In the cloned part we can perform whatever action we want, we could trace it full or parts of it, or log it. `tap` would be the basis for implementing more specific/customized/convenience tracing or logging APIs. `tap` could run concurrently so that it does not add any latency to regular path of the stream.

`tap` should look like:

```
tap :: IsStream t => (t m a -> m b) -> t m a -> t m a
```

The tap is mechanism to observe the stream at any point and do only some side effects, we cannot use the tapped stream for collecting results after processing it.

**Comment by pranaysashank** [comment]
v0.7.0 adds a `tap` combinator to `Streamly.Prelude`
```
tap :: (IsStream t, Monad m) => Fold m a b -> t m a -> t m a 
```
`Streamly.Internal.Prelude` exports a concurrent tap called `tapAsync`
```
tapAsync :: (IsStream t, MonadAsync m) => (t m a -> m b) -> t m a -> t m a
```
