### ISSUE TITLE
runStream  and "Run a streaming composition, discard the results." behaviour 

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#149]
I have been surprised by the discard of the results when you "runstream" : 
```
get  "/readWorkspaceIds" $ do
    workspaceIds <- (liftIO $ runStream $ Gsd.streamWorkspaceIds eventStoreContext )
    liftIO $ logInfo logger $ "[api] - result > " ++ show workspaceIds
    json workspaceIds
```
workspaceIds is always ()... what can I use instead to get the result ? something like sinkList...
Said differently,  How can I get the end result of my transformation flow then ?

**Comment by harendra-kumar** [comment]
You can use any of the folds described in the [documentation here](https://hackage.haskell.org/package/streamly-0.5.2/docs/Streamly-Prelude.html#g:9) . If you want to convert the stream into a list you can use the `toList` fold. However, as far as possible you generally want to do most of the processing inside the stream without getting out of it.

**Comment by harendra-kumar** [comment]
Note that `runStream` is just one of the folds that runs the stream for effects and discards the resulting values.

**Comment by nhenin** [comment]
Thanks !
