### ISSUE TITLE
Question : equivalent of flatMap with streamly ? piping streams without using runStream on mapM ?

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#154]
Here is the following code  : 

```
streamCommandConsumers ::  Logger -> EventStoreStreamRepository  -> EventStoreReading -> CommandHandler -> IO ()
streamCommandConsumers logger
                    streamRepository @ StreamRepository { aggregateIdStream, getCommandStream, getValidationStateStream }
                    Reading { streaming = Streaming {streamAllInfinitely, streamFromOffset},
                              querying = querying @ Querying {retrieveLast},
                              subscribing }
                    commandHandler =
  runStream $
    parallely
      $ streamAllInfinitely aggregateIdStream
      & S.mapM (\persistedAggregate -> do
        runStream $
         serially
          $ yieldAndSubscribeToAggregateUpdates subscribing getCommandStream persistedAggregate
          & S.mapM (\PersistedItem {item = aggregateId}  -> do
              let validationStateStream = getValidationStateStream aggregateId
              let commandStream = getCommandStream aggregateId
              lastOffsetConsumed <- liftIO $ getLastOffsetConsumed (retrieveLast validationStateStream)
              runStream $ serially $ (streamFromOffset commandStream $ fromMaybe 0 (fmap (+1) lastOffsetConsumed))))
```
I don't want to have to call runStream each time I'm using a mapM because it forces me to be on IO() , I would like all that process to stay somehow in the Stream Monad Transformer, is it possible ? If I return a stream inside the mapM I get nested stream and I don't see how I can flatMap.... I'm looking for a signature like this : 
`flatMap :: (IsStream t, MonadAsync m) => (a -> t m b) -> t m a -> t m b` instead of ``mapM :: (IsStream t, MonadAsync m) => (a ->  m b) -> t m a -> t m b``

**Comment by harendra-kumar** [comment]
PR #138 implements a concatMap which does what you want. I will merge it soon, but it may take a few weeks to upload the next release to hackage.

**Comment by nhenin** [comment]
ho great I will point directly on the commit when merged to master (which I'm doing now anyway for your lib now...)

**Comment by pranaysashank** [comment]
Closing this issue as `concatMap` has been introduced in `0.6.0`.
