### ISSUE TITLE
`Stream.parse` not exposed to user

### ISSUE THREAD

**Issue by xave** [composewell/streamly#1546]
ISSUE
Missing method yet examples still reference it.

BACKGROUND
I have been using the 0.7.2 version of Streamly where the `parse` function was exposed in Streamly.Internal.Prelude. In the Streamly.Internal.Data.Parser module, there is a function `sequence` that has a note that it is not implemented. As such, I moved to 0.8, specifically 0.8.2 to see what might be new. In the 0.8.2 version, the examples still reference Stream.parse (formally recommended to be qualified S.parse), yet the source code in Streamly.Prelude does not include it and the Streamly.Internal.Prelude where Stream.parse used to reside is now missing.

**Comment by xave** [comment]
Thank you Harendra.

**Comment by harendra-kumar** [comment]
This operation is slated to be released via `Streamly.Data.Stream` module in 0.9.0. Already present on master branch, to be released soon.
