### ISSUE TITLE
`concatMap`/`fromList` performance.

### ISSUE THREAD

**Issue by shlok** [composewell/streamly#1561]
Please look at the following program and the comment within it.

```haskell
module Main where

import Data.Function ((&))
import qualified Streamly.Prelude as S

main :: IO ()
main = do
  sum' <-
    S.enumerateFromTo (0 :: Int) 20000000000

      -- This single line slows down the program by 2.4x.
      & S.concatMap (\x -> S.fromList [x])

      & S.sum

  putStrLn $ "Sum: " ++ show sum'
```

Are there potential solutions?

Needless to say, this simple example serves to pinpoint a performance issue. In production code, here is what I actually do: Using a `scan`/`Fold`, keep track of a stream’s last element; if a certain relation holds between the last element and the current element, yield two elements (`[x, y]`) instead of one (`[x]`); finally `concatMap`/`fromList` as shown above. Such a massive slowdown for such a seemingly simple operation was unexpected; hence this issue.

Streamly 0.8.1.1.
GHC 8.10.4 (`-threaded -rtsopts -with-rtsopts=-N -O2`).

**Comment by harendra-kumar** [comment]
`concatMap` does not optimize well, [it is known](https://www.youtube.com/watch?v=foqUPiwMiOM). 

And this is the raison d'etre of Unfolds. Replace the offending line with this:

```
import qualified Streamly.Data.Unfold as Unfold

      & S.unfoldMany (Unfold.lmap (\x -> [x]) Unfold.fromList)
```

And watch the magic.

**Comment by shlok** [comment]
Ingenious and magical 😎. Thanks!
