### ISSUE TITLE
Consider changing the signature of replicateM unfold

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1599]
```
replicateM :: Applicative m => Int -> Unfold m (m a) a
```

If the replication count depends on the input e.g. when we have to resample an array
and we have to iterate as many times as the array length then we need the count to
be passed via unfold i.e. it should be `Unfold m (Int, m a) a`. We can use
`concatMap` to pass the count argument to `replicateM` but that won't perform
well.

**Comment by adithyaov** [comment]
`replicateM` is already released. We can create a new function and deprecate `replicateM`.

**Comment by adithyaov** [comment]
I've added `replicateM1`. We need to decide on the name. We can possibly keep both but that would be unnecessary maintainece overhead.

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/1896
