### ISSUE TITLE
Make ParallelT a special case of AsyncT

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#161]
ParallelT exists only as an unbounded version of AsyncT. It also makes sure that the concurrent streams start immediately without any delay. If we can guarantee that in AsyncT itself to a reasonable degree we can just remove ParallelT and use AsyncT with unbounded resources set via stateful config when needed.

With ParallelT gone, we can also change the name `AheadT` to `ParallelT`. Now, there would be only two flavors of concurrent streams:

* Parallel - meaning concurrent evaluation of stream actions but served in order
* Async - meaning concurrent evaluation of stream actions served in first first serve order

**Comment by pranaysashank** [comment]
From 0.7.0 ParallelT no longer has an unbounded buffer by default, the buffer for parallel streams is limited to 1500 by default, the same as other concurrent stream types. It can be changed using the `maxBuffer` directive.
