### ISSUE TITLE
Question : planning a new release soon ?

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#163]
Hi Guys, 

Are you planning a new release soon (> 0.5.2) ? There are so many new feature I would like to use ! :-) (the concatMap for example)... I'have tried to point on the last commit of your master branch, but I have issue with my IDE (Intellij)  :-( it is not showing me the code source... too bare to the metal for my sensitivity...

**Comment by harendra-kumar** [comment]
I have targeted quite a few things to the next release which can take more than a few weeks. But let me see if I can push one intermediate release quickly in the next few days.

**Comment by nhenin** [comment]
That would be great :-) btw I'm working on an open source application where I'm heavily using your lib (https://github.com/Eventuria/gsd)

**Comment by harendra-kumar** [comment]
@nhenin Happy new year! streamly-0.6.0 is on hackage now, enjoy! Good to hear that it is useful, we will be happy to solve any problems or add new stuff as needed.

**Comment by nhenin** [comment]
@harendra-kumar, happy new year to you and your team as well,  I really appreciate the reactivity and the quality of your answers :-) I wish you the best for 2019 !
