### ISSUE TITLE
Deprecate Streamly.Prelude

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1646]
In the new release the monomoprhically typed serial stream module `Streamly.Data.Stream` would replace `Streamly.Prelude`. Other stream types can be used by importing the corresponding monomorphically typed modules. Once all the functionality of `Streamly.Prelude` is transferred to these other modules and we have created the `Streamly.Data.Stream` and other stream modules (e.g. `Streamly.Data.Stream.Async`) then we can deprecate it.

**Comment by adithyaov** [comment]
See #2001 & #2007
