### ISSUE TITLE
Transition to Prim instead of Storable

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#1677]
For starters we can make some CPP macros for the `Foreign` to work with both Storable and Prim, Pinned and unpinned

**Comment by harendra-kumar** [comment]
* Remove Data.Array.Prim
* Remove Data.Array.Prim.Pinned
* Add support for dynamic pinning/unpinning the array (Data.Array.Foreign)

**Comment by harendra-kumar** [comment]
We are now using the Unboxed type class instead of Storable.
