### ISSUE TITLE
How to combine chunksOf and intervalsOf

### ISSUE THREAD

**Issue by Diamondy4** [composewell/streamly#1703]
I want to chunk input stream in lists of length X, with y sec timeout, so it'll have combined effect of `chunksOf x Fold.toList` and `intervalsOf y Fold.toList`. It should have semantics of "take up to x elements in y seconds in list" with resulting stream of lists. Can it be done with streamly?

**Comment by harendra-kumar** [comment]
yes, of course. Please check this out https://streamly.composewell.com/haddocks/streamly-0.8.2/Streamly-Internal-Data-Stream-IsStream-Reduce.html#v:chunksOfTimeout .
