### ISSUE TITLE
How to asynchronously interrupt a stream with another stream

### ISSUE THREAD

**Issue by sullyj3** [composewell/streamly#1704]
Suppose I have
```
count :: Serial Int
count = (Stream.delay 1 $ Stream.enumerateFrom 0)

stdinChars :: Serial Char
stdinChars = Stream.repeatM getChar

reset :: Serial ()
reset = () <$ (Stream.filter (== ' ') stdinChars)

main = do
  hSetBuffering stdin NoBuffering 
  hSetEcho stdin False
  -- ??
  pure ()
```

How would I write a program which counts upwards, restarting the count from 0 each time space is pressed? 

I have a vague idea of how I'd do this in Rx. Rx provides the operator `takeUntil`, which, rather than taking a predicate, takes a second stream, and terminates the original stream when the second emits output. Is there a streamly equivalent?

**Comment by harendra-kumar** [comment]
You can use StateT or a scan to share state between two streams. The state can then be reset by one of the streams and the effect will be visible in another. As an example of using StateT with streamly you can see this: https://github.com/composewell/streamly-examples/blob/0f4d8aa309670019bcf9d62774ccd9744f564b44/examples/AcidRain.hs .

**Comment by sullyj3** [comment]
Fantastic, thank you

**Comment by sullyj3** [comment]
For posterity, this is what I came up with:
```haskell
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE FlexibleContexts #-}

module Main where

import qualified Streamly.Prelude as Stream
import Streamly.Prelude (SerialT, MonadAsync)
import System.IO
import Control.Monad.IO.Class (liftIO)
import Control.Monad.State.Class
import Control.Monad.State (runStateT)

count :: (MonadAsync m) => SerialT m Event
count = Stream.delay 1 $ Stream.repeat Count

stdinChars :: MonadAsync m => SerialT m Char
stdinChars = Stream.repeatM $ liftIO getChar

reset :: (MonadAsync m) => SerialT m Event
reset = Reset <$ Stream.filter (== ' ') stdinChars

data Event = Count | Reset

handleEvents :: (MonadAsync m, MonadState Int m) => SerialT m ()
handleEvents = do
  event <- count `Stream.parallel` reset
  case event of 
    Count -> do
      liftIO . print =<< get
      modify (+1)
    Reset -> put 0

main = do
  hSetBuffering stdin NoBuffering 
  hSetEcho stdin False

  flip runStateT 0 $ Stream.drain $ handleEvents
```

One thing I'd like to do is factor this such that I end up with a single stream of resetting ints, that I can then further manipulate. I can't currently see a way to do that, since when I `case event of`, I'm forced to emit an int in both the `Count` and the `Reset` case, when I only want to emit one when I receive a `Count`. So I have to deal with the int immediately by printing it, and just emit `()` in both cases.

**Comment by sullyj3** [comment]
> One thing I'd like to do is factor this such that I end up with a single stream of resetting ints, that I can then further manipulate.

Revisiting this, I just needed `concatMapM`

```haskell
nums :: (MonadAsync m, MonadState Int m) => SerialT m Int
nums = (count `Stream.parallel` reset) & Stream.concatMapM handleEvent
  where 
    handleEvent = \case
      Count -> do
        modify (+1)
        (`Stream.cons` Stream.nil) <$> get
      Reset -> do
        put 0
        pure Stream.nil
```
