### ISSUE TITLE
chunksOfTimeout does not emit if stream is empty

### ISSUE THREAD

**Issue by Diamondy4** [composewell/streamly#1716]
chunksOfTimeout waits until at least one element in input stream and does not trigger provided fold on 0 elements when timeout happens. This looks like undesired behavior, or is there a way to force chunk folding on empty stream?

**Comment by Diamondy4** [comment]
Example
haskell```
main :: IO ()
main =
    Stream.repeat 5
        & Stream.delay 1000
        & StreamEx.chunksOfTimeout 10 1 Fold.length
        & Stream.mapM_ print
```

**Comment by harendra-kumar** [comment]
This is a bug, let me check if this can be worked around.

**Comment by harendra-kumar** [comment]
Currently `chunksOfTimeout` is implemented such that it flushes out any incomplete chunks within the timeout. If no chunk exists there is nothing to flush so nothing is emitted. This is a reasonable behavior if we want to use this API for flushing pending data for example when we are writing the stream to a file or to a network socket.

What you are expecting here is an alternative behavior where the expectation is to emit an empty output even if there was no pending chunk. Is that really what you want? Can you elaborate on the use case?

If it makes sense, it can be provided as an alternative behavior using a flag argument to the API.

**Comment by adithyaov** [comment]
@Diamondy4 You can probably play around with timestamping the required input, making timestamp a first-class citizen in your stream, and folding it according to your use case.

For example,
```
import Streamly.Internal.Control.Concurrent (MonadAsync)
import Streamly.Internal.Data.Stream.IsStream.Type (IsStream)

import qualified Streamly.Internal.Data.Stream.IsStream as Stream

{-# INLINE timeStampedInput #-}
timeStampedInput ::
       (IsStream t, MonadAsync m, Functor (t m))
    => Double -- Tick in seconds
    -> t m a
    -> t m (AbsTime, Just a)
timeStampedInput tick inp = timestampedInput `Stream.parallelFst` timeStream

    where

    timestampedInput = Stream.timestamped (fmap Just inp)
    timeStream = fmap (, Nothing) $ Stream.absTimesWith tick
```

```
main :: IO ()
main =
    Stream.repeat 5
        & Stream.delay 1000
        & Stream.timeStampedInput 1
        & Stream.mapM_ (print . snd)
```
The above would result in,
```
Just 5
Nothing
Nothing
Nothing
Nothing
...
```

You might need to fix the above code to compile but the idea is to generate a time stream in parallel to your stream and process the final stream accordingly.

**Comment by Diamondy4** [comment]
Thanks! I'll try this. Actually I just need to be able to stop (possibly infinite) stream on condition  like takeWhileM does, but on-demand, not as check after each new element (maybe as background check every X seconds).
I already can kill thread with infinite stream, but then data in processing will be lost. Will think how to do this more idiomatic with streamly.

**Comment by adithyaov** [comment]
> maybe as background check every X seconds

You can do that with the suggested method. Data in (mid) processing will always be lost if you want to end some operation mid-way, after some specific time.

**Comment by adithyaov** [comment]
`boundedIntervalsOf` needs to be implemented.

**Comment by adithyaov** [comment]
This PR https://github.com/composewell/streamly/pull/2849 defines the signature and documentation of `boundedIntervalsOf`
