### ISSUE TITLE
 convenience function `Prelude.tapBy`

### ISSUE THREAD

**Issue by sullyj3** [composewell/streamly#1732]
Every use I've ever made of `Prelude.tap` has been something like

```haskell
import qualified Streamly.Data.Fold as Fold
import qualified Streamly.Prelude as Stream

Stream.tap (Fold.drainBy logStreamContents)
  where
    logStreamContents :: a -> IO () 
```

It seems like it would be useful to have
```haskell
Streamly.Prelude.tapBy :: (IsStream t, Monad m) => (a -> m b) -> t m a -> t m a
```
To avoid having to import `Streamly.Data.Fold`, and otherwise make things more succinct. Would you accept a PR for this function?

**Comment by harendra-kumar** [comment]
There is already a function called `trace` with the same signature.

https://streamly.composewell.com/haddocks/streamly-0.8.2/Streamly-Prelude.html#v:trace

**Comment by sullyj3** [comment]
Ah, my mistake
