### ISSUE TITLE
Expose `Streamly.Data.Unboxed`

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#1733]

**Comment by adithyaov** [comment]
1. Rename the Unboxed APIs properly.
2. Rename `ArrayContents` properly

readByteArray -> peekWith
writeByteArray -> pokeWith
ArrayContents -> Memory or Storage or OAM (Offset Adressable Memory)

**Comment by harendra-kumar** [comment]
To be able to support different memory types, we can split the `Unboxed` type class in two classes:

* Unboxed: Specifying size and alignment for the type, this will be the same for all memory types. That way we can ensure that the size and alignment remain the same whichever method we use to read or write the type.
* Unbox: Specifying the read and write operations, this will be different for different memory types

We can then possibly have multiple `Unbox` type classes for different memory types:

* Array.Unbox operating on MutableByteArray#
* Foreign.Unbox operating on Ptr akin to Foreign.Storable
* ForeignPtr.Unbox operating on ForeignPtr (requires touching during read and write). This can be implemented in terms of the previous two.

We can then use the same common array code and pass the relevant type class dictionary to use a particular memory type. We could use a type class with two parameters one for memory type and one for the storable type, but that would make constraint types unnecessarily complex. And we would mostly need only the byte-array type class, others would not be used often. We only need a provision for those, just in case.

**Comment by harendra-kumar** [comment]
Alternatively, instead of creating a new type class for size and alignment, we can just reuse Storable and put a Storable constraint on Unbox. And make sure all instances are compatible with Storable. This will make the use of Storable and Unbox consistent. The downside is that to make an instance of Unbox you will also have to make an instance of Storable. However, if you are never going to use peek/poke you can leave those undefined and just specify size/alignment.

**Comment by adithyaov** [comment]
Common API naming:
newAligned
getInternal
cast
reallocAligned
asPtrUnsafe
putSliceUnsafe
cmp

**Comment by adithyaov** [comment]
The module should be renamed to `Streamly.Internal.Data.MutableByteArray`

**Comment by adithyaov** [comment]
Closed in https://github.com/composewell/streamly/pull/1772

**Comment by adithyaov** [comment]
We can keep this open as there is more discussion in this.

**Comment by adithyaov** [comment]
See #1910
