### ISSUE TITLE
Repurpose the streamk build flag

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1737]
Currently this flag enables USE_STREAMK_ONLY cpp macro. We should remove all usage of that macro.

Use the `streamk` build flag to disable rewrite-rules instead i.e. enable the DISABLE_FUSION macro when using this flag. Make sure that we disable all rewrite rules when this macro is used. This way we can test the code paths that kick in when rewrite rules do not fire.

**Comment by rnjtranjan** [comment]
Fixes:https://github.com/composewell/streamly/issues/1737
