### ISSUE TITLE
retrieving the last value executed by a runStream

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#174]
Hi, 

do you have a function that does the following behaviour ? : 

`runStreamAndReturnLastElementStreamed :: (IsStream t, Monad m) => t m a -> m a`

it runs the stream t m a and return the last value before the stream ends.

Thanks !

**Comment by harendra-kumar** [comment]
It is `last`:

```
last :: Monad m => SerialT m a -> m (Maybe a) #

Extract the last element of the stream, if any.

Since: 0.1.1
```

**Comment by harendra-kumar** [comment]
I hope you got what you wanted.
