### ISSUE TITLE
Write a test for aligned Unboxed array

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1752]
I am not sure if byte offset based addressing would work correctly in all cases. May depend on how GHC implements alignment in arrays. Does it always allocate contiguous/packed elements or leaves unused bytes in between due to alignment? We can create a test case to make sure we are fine:

* Create  a type with size 1 byte and alignment 8 bytes.
* Create an array with multiple elements of this type
* Read it back and compare with original values

**Comment by adithyaov** [comment]
Verified in https://github.com/composewell/streamly/pull/1781
