### ISSUE TITLE
Using MonadResource with streamly

### ISSUE THREAD

**Issue by shlok** [composewell/streamly#180]
I am unable to use `ResourceT IO` as my monad in streamly’s `unfoldrM` (or anything that requires `MonadAsync`) because ResourceT [no longer implements MonadBaseControl](https://www.snoyman.com/blog/2018/02/conduitpocalypse) (they moved to MonadUnliftIO instead).

How would you recommend going about resource allocation with streamly?

**Comment by harendra-kumar** [comment]
@shlok resource allocation/cleanup is still to be implemented natively in streamly. Until that happens, can you use an older version of resourceT instead?

**Comment by shlok** [comment]
@harendra-kumar That seems to work, thanks! (This older version of resourcet even compiles against the latest Stack resolver without issues.)
