### ISSUE TITLE
`maxThreads` ignored unless `Rate` is also specified.

### ISSUE THREAD

**Issue by luke-clifton** [composewell/streamly#181]
```
λ S.runStream . S.maxThreads 1 . S.asyncly $ S.replicateM 5 (threadDelay 1000000)
(1.01 secs, 722,616 bytes)
λ S.runStream . S.avgRate 10000 . S.maxThreads 1 . S.asyncly $ S.replicateM 5 (threadDelay 1000000)
(5.02 secs, 736,720 bytes)
```

I would expect both of these to take 5 seconds due to `maxThreads 1` in both of them.

**Comment by luke-clifton** [comment]
```
λ S.runStream . X.inspectMode . S.maxThreads 1 . S.asyncly $ S.replicateM 5 (threadDelay 1000000)
SVar Done
Creator tid = ThreadId 11244
style = AsyncVar
---------CURRENT STATE-----------
outputQueue length computed  = 0
outputQueue length maintained = 0
outputDoorBell = Nothing
needDoorBell = True
running threads = fromList []
running thread count = 0
---------STATS-----------
total dispatches = 6
max workers = 6
max outQSize = 10
(1.02 secs, 1,013,248 bytes)
```

Does `maxThreads` correspond to `max workers`?

**Comment by harendra-kumar** [comment]
@luke-clifton that indeed seems like a bug, thanks for reporting. Yes, max workers value in the stats is the peak number of threads reached at any given point, this should correspond to `maxThreads`. Note, this stat may not be exact as in certain conditions some workers may return without doing any work. But most of the time this is almost accurate.

**Comment by harendra-kumar** [comment]
This seems to have been introduced by a fix for a rate control issue:

```
commit cca869f7ed98fbe513cff1e67635917f9e16e113
Author: Harendra Kumar <harendra.kumar@gmail.com>
Date:   Wed Sep 12 11:13:56 2018 +0530

    Fix a rate control issue
    
    We were not sending enough workers in the end when the streaming is finishing.
    Also, limit the estimated workers to the number of yields required.
```

After the above commit, in `dispatchWorker` we are not taking into account how many workers are already active, earlier we were doing that. This is what we did in the fix that introduced this bug:

```
-                Limited lim | active < (fromIntegral lim) -> dispatch
+                Limited lim | lim > 0 -> dispatch
```

I think, the right fix is to use the old code when rate control is not being used and the new code when rate control is being used.

@luke-clifton do you want to try fixing it?

**Comment by luke-clifton** [comment]
Even with rate control, don't you want to obey the `maxThreads` limit?

In [the docs for `rate`](http://hackage.haskell.org/package/streamly-0.6.0/docs/Streamly.html#v:rate) you say that the effective maximum rate that can be achieved is governed by `maxThreads`.

**Comment by harendra-kumar** [comment]
With rate control it's handled elsewhere in dispatchWorkerPaced. It already works as intended.
