### ISSUE TITLE
Introduce a streamly-core flag in bench-runner to not build streamly

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1816]
Only build streamly-core. This will save a lot of time when running benchmarks after changing streamly-core. With this flag benchmarks will be built with --use-streamly-core. Similar flag can be added to test-runner as well.

**Comment by harendra-kumar** [comment]
Pssing `--cabal-build-options "--flag use-streamly-core" to bench-runner works now. We only need to remove `streamly-docs` from cabal.project to avoid building streamly. Maybe we can use the `use-streamly-core` flag in streamly-docs to avoid that.

**Comment by rnjtranjan** [comment]
It is verified that any change in streamly-core  rebuilds  streamly-core only.

$./bench-runner --cabal-build-options "--flag use-streamly-core" --targets Data.Stream --prefix o-1-space.mappingX4.trace 
Using git-cabal for branch specific builds
"Using targets [Data.Stream]"
renamed 'charts/Data.Stream/results.csv' -> 'charts/Data.Stream/results.csv.prev'
git-cabal v2-build --flag fusion-plugin --flag limit-build-mem --with-compiler ghc --flag use-streamly-core --enable-benchmarks streamly-benchmarks:bench:Data.Stream
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - streamly-core-0.1.0 (lib:streamly-core) (file src/Streamly/Internal/Data/Stream/Expand.hs changed)
 - streamly-benchmarks-0.0.0 (lib) (dependency rebuilt)
 - streamly-benchmarks-0.0.0 (bench:Data.Stream) (dependency rebuilt)
Preprocessing library for streamly-core-0.1.0..
Building library for streamly-core-0.1.0..
