### ISSUE TITLE
Use stream instead of list in eqBy parser

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1845]
Use a stream instead of a list so that we can use any container type.

```
eqBy :: Monad m => (a -> a -> Bool) -> [a] -> Parser m a ()
```

Should become:

```
eqBy :: Monad m => (a -> a -> Bool) -> Stream m a -> Parser m a ()
```

**Comment by adithyaov** [comment]
We already have `matchBy` that does the same. 

Benchmarks:

ParserD:
```
   eqBy:                                         OK (0.43s)
      6.64 ms ± 235 μs
    matchBy:                                      OK (0.42s)
      6.42 ms ± 199 μs
```

Parser:
```
    eqBy:                                       OK (0.21s)
      6.79 ms ± 424 μs
    matchBy:                                    OK (0.42s)
      6.50 ms ± 494 μs
```

Do we want to keep both `matchBy` and `eqBy`?
Should we remove `eqBy` and rename `matchBy` to `eqBy`?

**Comment by adithyaov** [comment]
Also, see https://github.com/composewell/streamly/pull/1894

**Comment by adithyaov** [comment]
We can keep this as it is. Too much thought into this is unecessary.
