### ISSUE TITLE
Equivalent of Streaming.effect?

### ISSUE THREAD

**Issue by adamConnerSax** [composewell/streamly#187]
I'm trying to do `(Monad m, IsStream t)=> m (t m b) -> t m b` which is, more or less, called "effect" in the Streaming library.
I can do 
```
import qualified Streamly as S
import qualified Streaming.Prelude as S
effect :: (S.IsStream t, Monad m) => m (t m b) -> t m b
effect x =  S.concatMap (const x) (S.yield ())
```
which is fine but seems needlessly indirect.  Am I missing the appropriate library function?  I hunted around some...

**Comment by harendra-kumar** [comment]
There is no such API as of now. I never felt a need for something like this. We can consider adding it if it has a good use case. Can you describe your use case?

**Comment by adamConnerSax** [comment]
Thanks!  I'll close this, then.  But I do think it's be a useful thing to point out in the docs if there's a good place to do so.
