### ISSUE TITLE
Cycle in stream graph

### ISSUE THREAD

**Issue by mryndzionek** [composewell/streamly#188]
Hello,
I would like to use streamly in a simulation that incorporates bidirectional communication. This translates into a cycle in the stream processing graph.  It seems that currently there's no combinator for this. My question is: how to best achieve this functionality? Is adding `Control.Monad.Fix` to streamly a good idea? Maybe I should use `Control.Concurrent.Chan` to implement this "loop"?

Help is greatly appreciated.

**Comment by harendra-kumar** [comment]
You are right, cycles in the graph are not supported yet. This is a pending feature and is planned for future releases. I am not sure yet how we will end up implementing it ultimately.

You can try using a `Chan`, `MVar` or `IORef` to achieve this functionality. You may also want to take a look at the `fromSVar` and `toSVar` internal APIs in streamly, these APIs are not exposed but may be relevant in this context if you are inclined to hack the internals of streamly.

**Comment by mryndzionek** [comment]
Thank you very much for quick response! Good to hear that this is planned functionality. I'll take a look at the internal APIs. Thanks again! Streamly is great!
