### ISSUE TITLE
Performance when comparing streams

### ISSUE THREAD

**Issue by Magalame** [composewell/streamly#189]
Hi!

I'm trying to wrap my head around Streamly, and I'm trying to efficiently compare two Streams, but cannot get satisfying performances. There is probably something obvious I'm missing:
```
import Streamly
import qualified Streamly.Prelude as S
import Data.Function ((&))

xs = S.fromFoldable ([1..600000] :: [Double])
ys = S.fromFoldable ([1..600000] :: [Double])

xt = [1..600000] :: [Double]
yt = [1..600000] :: [Double]

S.toList $ asyncly $ S.zipWith (==) xs ys & S.notElem False -- takes (0.68 secs, 2,194,017,856 bytes)

xt == yt -- takes (0.18 secs, 202,012,472 bytes)
```

Thanks!
```

**Comment by harendra-kumar** [comment]
For a fair comparison:

* use `S.enumerateFromTo` instead of `S.fromFoldable` to generate the streams
* use `S.eqBy (==)` for comparing streams instead of using `zipWith`
* compile using `-O2`

Please report the results with the above changes.

**Comment by Magalame** [comment]
Here's what I have eventually, with `-O2` along with the [other recommended flags](https://github.com/composewell/streamly/blob/master/docs/Build.md)

With streams/fromFoldable:
```
xs = S.fromFoldable ([1..600000] :: [Double])
ys = S.fromFoldable ([1..600000] :: [Double])

main = do
    s <- S.notElem False $ asyncly $ S.zipWith (==) xs ys
    print s
```
total time  =        0.05 secs   (189 ticks @ 1000 us, 8 processors)
total alloc = 288,176,280 bytes  (excludes profiling overheads)

With streams/enumerateFromTo:
```
xs = S.enumerateFromTo 1 600000 :: AsyncT IO Double
ys = S.enumerateFromTo 1 600000 :: AsyncT IO Double

main = do
    s <- S.eqBy (==) xs ys
    print s
```
total time  =        0.09 secs   (346 ticks @ 1000 us, 8 processors)
total alloc = 624,176,872 bytes  (excludes profiling overheads)

With plain lists:
```
```
total time  =        0.03 secs   (127 ticks @ 1000 us, 8 processors)
total alloc = 201,776,768 bytes  (excludes profiling overheads)

**Comment by pranaysashank** [comment]
How are you running these programs? On my machine Streamly shows better performance than standard lists, even with `zipWith`.
```Haskell
-- Issue.hs
module Main where

import           Streamly
import qualified Streamly.Prelude as S

xs, ys :: AsyncT IO Double
xs = S.enumerateFromThenTo 1 2 600000
ys = S.enumerateFromThenTo 1 2 600000

xt = [1..600000] :: [Double]
yt = [1..600000] :: [Double]

main :: IO ()
main =  S.eqBy (==) xs ys >>= print

list :: IO ()
list = print $ xt == yt
```
## Streamly `eqBy`
```bash
ghc -package streamly-0.6.1 --make Issue.hs -main-is main -O2`
time ./Issue +RTS -s -RTS
```
Output:
```
True
51,312 bytes allocated in the heap
44,576 bytes maximum residency (1 sample(s))

real	0m0.027s
```
## Standard Haskell lists
```bash
ghc -package streamly-0.6.1 --make Issue.hs -main-is main -O2`
time ./Issue +RTS -s -RTS
```
Output:
```
True
76,851,488 bytes allocated in the heap
44,576 bytes maximum residency (2 sample(s))

real	0m0.051s
```

What version of streamly are you on?

**Comment by Magalame** [comment]
Thanks for the quick and detailed answer! I was compiling with `-prof, rendering the benchmarks inaccurate.

I have a follow up question. In the case where we actually deal with `S.fromFoldable`, it seems that `AsyncT` doesn't do better than `SerialT`:
```
module Main where

import           Streamly
import qualified Streamly.Prelude as S

xs, ys :: AsyncT IO Double
xs = S.fromFoldable [1..600000]
ys = S.fromFoldable [1..600000]

xt, yt :: SerialT IO Double
xt = S.fromFoldable [1..600000]
yt = S.fromFoldable [1..600000]

asyn:: IO ()
asyn =  S.eqBy (==) xs ys >>= print

seria :: IO ()
seria =  S.eqBy (==) xt yt >>= print
```

and I can't wrap my head around why is that so

**Comment by pranaysashank** [comment]
```haskell 
generate = S.fromFoldable [1..600000]
```
Here, `generate` is essentially a pure function that returns its values immediately, i.e. there is no computation that need to happen to return the next element in the stream, there is no delay in generating the next element, in such a case streamly need not spin extra workers to meet the demand from the consumer.

In such cases involving pure functions, streamly's concurrent combinators are equivalent to `serially`.

**Comment by Magalame** [comment]
I see! So `serially` already yields the best performances in this case? I was hopping to compare the elements of the two streams asynchronously

**Comment by pranaysashank** [comment]
> I was hoping to compare the elements of the two streams asynchronously

In this example, if you want the comparison to be asynchronous, one way I can think of is to partition the streams and then run the comparison in the partitions concurrently.

In what is a very contrived example:
```Haskell
module Main where

import           Streamly
import qualified Streamly.Prelude as S

a,b :: [Int]
a1,b1,a2,b2 :: Int

a = [1..1000000000]
b = [1..1000000000]

-- partitioning a and b in half

a1 = 1
a2 = 500000000
a3 = 1000000000

b1 = 1
b2 = 500000000
b3 = 1000000000

xxs :: Int -> Int -> Int -> Int -> AsyncT IO ()                                                                                   
xxs a1 a2 b1 b2 =                                                                                                                 
    S.yieldM $ do                                                                                                                 
        x <-                                                                                                                      
            S.eqBy                                                                                                                
                (==)                                                                                                              
                (S.enumerateFromTo a1 a2 :: SerialT IO Int)                                                                       
                (S.enumerateFromTo b1 b2)                                                                                         
        print x 

pcomp :: IO ()
pcomp = runStream $ adapt $ xxs a1 a2 b1 b2 `async` xxs (a2 + 1) a3 (b2 + 1) b3

lcomp :: IO ()
lcomp = print $ a == b
```

Compiling the usual way with `-O2` I have,

- Streamly `eqBy`

```
73,368 bytes allocated in the heap
49,504 bytes maximum residency (1 sample(s))

real	0m0.786s
```

- Standard Haskell lists

```
80,000,051,360 bytes allocated in the heap
44,576 bytes maximum residency (2 sample(s))

real	0m13.192s
```

Do you have a specific use case, other than the curiosity to see if `async` gives the better performance?

**Comment by Magalame** [comment]
Thanks for the details!

I actually have a specific use case. I'm trying to see if using `streamly` can improve the performances of [analyze](http://hackage.haskell.org/package/analyze) (a library providing simple data frames). Currently the data of the frames is stored as a `Vector` of `Vector`s, and [this issue](https://github.com/DataHaskell/dh-core/issues/35) suggest s evaluating the performances of a stream of vectors instead.

And the first thing I'm trying to implement is the `==` operator. I should have said it before but `S.enumerateFromTo` although efficient is probably not suited to handling empirical data.

**Comment by Magalame** [comment]
ping @pranaysashank

**Comment by pranaysashank** [comment]
My above solution should still work, `Vector` can be partitioned in O(1) time, due to O(1) indexing (so you can use fromFoldable with different slices from the vector). 

However, I don't think you'd need the comparisons themselves to be concurrent at this level, concurrency would probably be handled at a higher level in the library. I'm also not familiar with DataHaskell.

**Comment by Magalame** [comment]
I see. Thanks again for your precious help!

**Comment by pranaysashank** [comment]
@Magalame If you have any further questions, feel free to reopen this issue or drop by the Gitter chat room.

**Comment by Magalame** [comment]
@pranaysashank thanks! I won't hesitate, it is possible we try to implement data frames with `streamly`, and I'll probably some questions!

**Comment by harendra-kumar** [comment]
@Magalame I just merged quite a few commits with major enhancements to master and more will be coming this week. See the changelog and also build the haddocks to check out the new stuff. Especially, the `Streamly.Fold` module in the new changes has stream splitting, partitioning and distributing feature. This could be very handy in implementing data frames. File IO related APIs will be coming this week or the next to master.

**Comment by Magalame** [comment]
Ooh great! The IO API will be interesting to load/save data efficiently, I'm hyped now
