### ISSUE TITLE
Uniq off by one element?

### ISSUE THREAD

**Issue by RichardWarfield** [composewell/streamly#191]
First of all, thank you for this fantastic library.  

I seem to have encountered an issue with the `Streamly.Prelude.uniq` function, where the first item on the stream is repeated and subsequently the stream lags by one element:

```
λ= [109]: runStream $ S.mapM print $ S.uniq $ 1 `S.cons` 2 `S.cons` 3 `S.cons` S.nil                                                                         
Out [109]: 
1
1
2
```

Whereas without the `uniq` I get:

```
λ= [108]: runStream $ S.mapM print $ 1 `S.cons` 2 `S.cons` 3 `S.cons` S.nil                                                                                  
Out [108]: 
1
2
3
```

Using streamly 0.6.1 from Hackage.

I would expect the two to have the same result provided there are no repeated elements.

**Comment by pranaysashank** [comment]
Thanks for reporting this bug. I must have introduced this one, I’ll push the fix, have to yield a different element and add tests, but it might take a while before it lands in a new release.
