### ISSUE TITLE
Use Bool type instead of Switch type

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1961]
@adithyaov suggests that we use a `Bool` (True/False) instead of `Switch` (On/Off) to avoid importing another type. This will have to be used in, the FileSystem.Event module, Concurrent options, Network API options, and also in the `streamly-coreutils` package. If we have to change it we have to change it now before we release the type.

Pros:
* On/Off are a bit more explicit/intuitive for binary settings
* On/Off are shorter to type than True/False

Cons:

* it requires importing the Switch type for type annotations

**Comment by adithyaov** [comment]
`True` and `False` can be very intuitive if the options are named properly.
The option should be in the form of a boolean question.
The option should almost be verb-ish.
For any option, if any of the following makes sense, `True` and `False` should
make sense.

* Let us <option>
* Let us be <option>
* Let us make <option>

`be` and `make` are positives and are generally the default in a programmers
mind.

For example, `followLinks` sounds intuitive with `True` and `False`.
`Let us follow-links` makes sense.

Consider `recursive`.
Let us be `recursive` makes sense.
`recursive` also is a good option name.
To make it more explicit, we can rename it to `beRecursive` or `makeRecursive`
depending on the context.

`force` is a good option name.
`Let us force` sounds good.

`set*` is a good option name.
`Let us set*` sounds good.
