### ISSUE TITLE
The following modules should be removed/moved accordingly

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#1969]
`Streamly.Internal.Data` is the assumed prefix.
* **Mv** Stream.ZipAsync -> Stream.Zip.Concurrent
* **Rm** Stream.Serial 
* **Rm** Stream.IsStream.*
* **??** Stream.Parallel 
* **??** Stream.Ahead
* **Mv** Fold.Async -> Fold.Concurrent

**Comment by adithyaov** [comment]
These are internal modules. This is not a blocker for the release.

**Comment by adithyaov** [comment]
We need to update all the tests and benchmarks first.

**Comment by harendra-kumar** [comment]
Mostly deprecated or renamed now.
