### ISSUE TITLE
API Changelog links are broken.

### ISSUE THREAD

**Issue by philderbeast** [composewell/streamly#1970]
API Changelog links on https://streamly.composewell.com/streamly-0.8.2/Changelog.html are broken:

https://streamly.composewell.com/streamly-0.8.2/API-changelog.html

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9GP69JX1RE0GCY7H</RequestId>
<HostId>KEjzIRSRbpFU8CEJeFjgaC0Gn7xw2Gk6165F9fNE4q5u3mZ6F+mIUjYB/BHNI+dZjnKem7CZ8k8=</HostId>
</Error>
```

**Comment by adithyaov** [comment]
https://github.com/composewell/streamly/pull/1861/files#diff-9c116d4aeede361f865182a966b23b62a08d61ecae063691999b8b56bb4769bbR28 should fix that. The next update of the website will fix the link.
Until then, please look at, https://github.com/composewell/streamly/blob/v0.8.2/docs/API-changelog.txt for 0.8.2 API-changelog

**Comment by harendra-kumar** [comment]
Need to fix this for hackage as well if possible for the 0.9.0 release.
