### ISSUE TITLE
Fix the example in Streamly.Network.Socket module

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#1978]
And make it a docspec.

**Comment by adithyaov** [comment]
Is this still a valid issue? I found only one example that needed to be made a docspec,

**Comment by harendra-kumar** [comment]
It is still valid. There is an example at the top of the module.

**Comment by adithyaov** [comment]
This was linked incorrectly. Needs to be reopened if Github closes it after the merge.
