### ISSUE TITLE
String.hs APIs to be implemented

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#199]
Implement the undefined APIs in String.hs especially  decodeUtf8/encodeUtf8 and the utility operations. Skip `decodeWith`. 

The unicode aware operations are lower priority for now. In fact, we may want to move them to a separate package like `unicode-transforms`, so as to use a common unicode database for all unicode operations. We can even implement unicode-transforms/normalization using streamly, I guess it would be a more succinct implementation.

**Comment by pranaysashank** [comment]
encodeUtf8/decodeUtf8 has been implemented, closing this issue as it is now superseded by #269
