### ISSUE TITLE
Improve deprecation message in Streamly.Prelude .

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2012]
In the following message:

```
Deprecated: Please use Streamly.Data.Stream, Streamly.Data.Stream.Concurrent, & Streamly.Data.Stream.Time instead.
```

The link to `Streamly.Data.Stream` does not work (re-exported module), also `Streamly.Data.Stream.Time` does not exist.

**Comment by adithyaov** [comment]
This is already resolved.
