### ISSUE TITLE
Rename Data.Array.Unboxed to just Data.Array

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2040]
Because unboxed is the most common use case. The generic array can be named as "Data.Array.Generic".

As @twitu suggested earlier.

**Comment by adithyaov** [comment]
We can do the following for now,
- Rename `Streamly.Internal.Data.Array` to `Streamly.Internal.Data.Array.Boxed`
- Rename `Streamly.Data.Array` to `Streamly.Data.Array.Boxed`and hide it, (`other-modules`)
- Rename `Streamly(.Internal).Data.Array.Unboxed(.Mut)` to `Streamly(.Internal).Data.Array(.Mut)`
