### ISSUE TITLE
Unexpose `Fold.concatMap`

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#2056]

**Comment by adithyaov** [comment]
# Problems

- We can't un-expose it.
- We need to deprecate `concatMap`

# Questions

- What should the upgrading guide say?
- How do users use the new code?

# Possible solutions

- We can deprecate it and suggest they modify their code to use `ParserK`
  instead?
- Introduce a `FoldK` and then deprecate it.
- Of course, we wouldn't be able to convert a `FoldK` to a `Fold`. Or a
  `ParserK` to a `Fold`.
- They would still need to modify their code but maybe not as much.

- We can indefinitely deprecate `concatMap` and say we do not support this
  operation anymore but also we won't remove it.
- But then people will never change their code.

**Comment by harendra-kumar** [comment]
Should remain as is.
