### ISSUE TITLE
Review `Streamly.Data.Fold`

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#2057]
- [x] Rename `foldr` to `foldr'`
- [x] Rename `drainBy` to `drainWith`
- [x] Change the doc of `index`. It refers to `Streamly.Prelude`
- [x] `Streamly.Prelude` is referenced in the docs
- [x] Rename `serialWith` to `splitWith`
- [ ] Rename `partitionBy` to `partitionWith` (Internal)
- [ ] Un-expose `concatMap` (https://github.com/composewell/streamly/issues/2056)

**Comment by harendra-kumar** [comment]
I have already done many of these changes. Some are left.
