### ISSUE TITLE
Keep functions like `replicateM` and `repeatM` hidden

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#2074]
- It becomes very confusing when we think about the concurrency aspect.
- Concurrent `repeatM` is `Concur.mapM Stream.repeat` or `Concur.sequence Stream.repeat`
- But if `Stream.repeatM` is in the picture, this idiom is hard to think of. 
- Explicitly specifying how to sequence gives a better intuition of how things work.

**Comment by harendra-kumar** [comment]
How about adding repeatM and replicateM to Cocnurrent module then?

**Comment by harendra-kumar** [comment]
We have added these to concurrent module, this issue is irrelevant now.
