### ISSUE TITLE
Add a dual of StreamT

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#21]
The `StreamT` type composes first element of the outer loop with all the elements in the inner loop and then goes ahead with the second element of the outer loop. There is a dual possible where we can compose the first element of the inner loop with all the elements of the outer loop and then do the same with the second element of inner loop.

```
x <- [1,2]
y <- [3,4]
return (x,y)
```
StreamT produces `(1,3) (1,4) (2,3) (2,4)` whereas the dual will produce `(1,3) (2,3) (1,4) (2,4)`.

This has the effect of inverting the order of the loops without changing the code. In many cases the efficiency of the program may matter depending on the order of the loops. The dual of StreamT can help in inverting the order by just changing the type just like all other streamly stream types work.

What do we call the type? CoStreamT, InverseT, InverseStreamT? The combinator for this could be `inversely`?

Another possibility could be to have a combinator that just flips the current order?

**Comment by hussein-aitlahcen** [comment]
Looking at #22, `CoSerialT` would be great !

**Comment by harendra-kumar** [comment]
Sounds good.

**Comment by harendra-kumar** [comment]
This is not much useful as discussed in #44. Closing it.
