### ISSUE TITLE
Improve the module deprecation messages

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#2105]
- Streamly.Internal.Data.Stream.IsStream.*
- Streamly.Prelude
- Streamly.Internal.Data.Stream.Serial
- Streamly.Internal.Data.Stream.Async
- Streamly.Internal.Data.Stream.Parallel

**Comment by harendra-kumar** [comment]
""Please use \"Streamly.Data.Stream\", \"Streamly.Data.Stream.Concurrent\", & \"Streamly.Data.Stream.Time\" instead."

Suggest Corresponding Internal modules, these modules are not exposed. Also add the Exception.Lifted module.

**Comment by harendra-kumar** [comment]
Also say from which package (streamly or streamly-core) these modules are to be used.
