### ISSUE TITLE
Stream Error Handling

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#212]
Hi, 
I remember at the beginning of 2019, @harendra-kumar you said to me that error handling was not fully handled properly especially for parallel streams and that it was on the roadmap (Sorry somehow I'm not able to find this issue where we discussed about it....).

Could you give us some status regarding that feature ?

Thanks.

**Comment by harendra-kumar** [comment]
The only thing that was not done at that time was catching errors inside the stream monad. It is done now along with a lot more stuff. You can take a look at the changelog and the haddock documentation of the master branch. See `bracket`, `onException`, `finally`, `handle` etc. in `Streamly.Prelude` module.  We will make a release soon, maybe within next couple of weeks. Until then you can use the code from the master branch.

**Comment by nhenin** [comment]
ok Thanks for the answer :-)
