### ISSUE TITLE
Example request: Read file into hashmap

### ISSUE THREAD

**Issue by tkvogt** [composewell/streamly#216]
A lot of people should have the same problem: How to stream the lines of a file into a map-like structure? Assume a file is given, consisting of unique names, I need to assign an index to every name. I then use this hashmap in another stream to replace names with indexes.

What I have come up so far misses the folding part:
```
import           Streamly
import qualified Streamly.Prelude as S
import qualified Streamly.Fold as FL
import qualified Streamly.Mem.Array as A
import qualified Data.HashMap.Strict as H
import           Data.HashMap.Strict(HashMap)

genHashmap :: HashMap Text Int -> (FilePath, Int) -> IO (HashMap Text Int)
genHashmap hmap (source, i) =
    fold ?
    $ S.zipWith (\n c -> (n,c))
                (S.fromFoldable [i..])
    $ FL.splitSuffixBy (== ord' '\n') A.toArray
    $ File.read source
```

**Comment by pranaysashank** [comment]
Assuming you have to update the hashmap `hmap`, I think a fold like
`S.foldl' (\hm (n, c) -> H.insert n c hm) hmap` should work.

Also looks like the function in zipWith should flip the arguments.

**Comment by tkvogt** [comment]
That was easier than I thought. Thanks!
