### ISSUE TITLE
rename StreamT to SerialT?

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#22]
Currently all the stream types reflect the nature of the stream except `StreamT` which is a generic name even though the combinator for it is called `serially`. It will be consistent with the rest of the naming, with the combinator as well as reflect the nature of the stream if we call it `SerialT` instead. Though it will not have stream in its name but neither do other types.

**Comment by harendra-kumar** [comment]
For the record this type is exactly the same as any other `ListT` so it can also be called that I would rather keep it consistent with other names and the combinator. Another option is to keep the type `StreamT` and rename the combinator as `streamly` but that again sounds generic and does not reflect how this type composes.

**Comment by afcowie** [comment]
I'd encourage you to change the name; I was expecting StreamT to be the general underlying type and as I was reading through the tutorial discovered it wasn't particularly special. Good call.

**Comment by afcowie** [comment]
(as an aside, similar vein: I briefly wondered if ParallelT was going to fire off sparks with `parMap` or similar, as much else was described in terms of threads and Haskell concurrency "perhaps this one employs Haskell parallelism?!?")

**Comment by harendra-kumar** [comment]
@afcowie thanks for confirming my question mark in this issue :-) In fact there is a generic type internally called `Stream` that represents all types of streams and we convert to and from that type to other types. So I was uncomfortable that this name has potential to confuse. I want to keep things as intuitive as they can be so that you do not have to read the docs all the time.

**Comment by harendra-kumar** [comment]
Good and short names are hard to find, there are existing biases like the sparks thing you mentioned. I am not particularly a fan of  `AsyncT` vs `ParallelT`. The name `async` does not fit so well with the concept of demand based parallelism, it has existing usage that can confuse easily, I am wondering if there can be a better option?

**Comment by harendra-kumar** [comment]
At the same time we should change `ZipStream` to `ZipSerial`.
