### ISSUE TITLE
Test that manual Unbox instances and generic derived instances are equivalent

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2215]
For all manual instances:

* sizeOf x == genericSizeOf x
* writing with pokeByteIndex and reading with genericPeekByteIndex produces the original value
* writing with genericPokeByteIndex and reading with peekByteIndex produces the original value

**Comment by rnjtranjan** [comment]
Looks like we can't test it as it requires an instance of SizeOfRep which is (*->*):
getting below error:
No instance for (SizeOfRep (Rep Int))
        arising from a use of ‘genericSizeOf’
    • In the second argument of ‘(==)’, namely
        ‘genericSizeOf (Proxy :: Proxy Int)’
      In the first argument of ‘assert’, namely
        ‘(sizeOf (Proxy :: Proxy Int)
            == genericSizeOf (Proxy :: Proxy Int))’
      In a stmt of a 'do' block:
        assert
          (sizeOf (Proxy :: Proxy Int) == genericSizeOf (Proxy :: Proxy Int))
   |
53 |     assert (sizeOf (Proxy :: Proxy Int) == genericSizeOf (Proxy :: Proxy Int))

**Comment by harendra-kumar** [comment]
You can test instances other than the primitive types.
