### ISSUE TITLE
Hide some modules before releasing 0.7.0

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#222]
We need to hide the following modules as they are not yet finalized and changes to them later may to breakage in the next release:

* Streamly.FileSystem.FD
* Streamly.FileSystem.File
* Streamly.Pipe
* Streamly.Time.Clock
* Streamly.Time.Units

We also need to update the README because some examples in it are currently based on `Streamly.FileSystem.File`. Also need to see there are any other examples/details in README that need to be updated to keep it in sync with the code. We will have to revert that later after the release.

There are also some comments on README sent to me by @neongreen that I have to incorporate.

**Comment by pranaysashank** [comment]
The module structure has changed significantly and this is no longer applicable, should create another issue to track the updates to README and examples.
