### ISSUE TITLE
A PinnedArray type?

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2245]
To make the pin/unpin conversion explicit we can introduce a PinnedArray type. IO routines would use a PinnedArray type. A pinned array can be either converted to unpinned (copying) or cast into unpinned (without copying). Similarly an unpinned array can be force into a pinned array, it will copy it if the underlying memory is unpinned otherwise just cast it.

Operations:

```
unpin :: PinnedArray -> Array 
cast :: PinnedArray -> Array
pin :: Array -> PinnedArray
```

PinnedArray is always guaranteed to be pinned but Array may use pinned or unpinned as underlying memory.

**Comment by adithyaov** [comment]
This is essentially a `newtype`.
newtypes are good to distinguish properties of types but we shouldn't overuse it.

Pros & Cons I can think of.

Pros:
- A new type is more explicit.
- A user can make a more informed decision if the internal unsafe APIs are used.

Cons:
- Unecessary info to the users.
- Maintainence overhead.
- Arrays will be slightly more harder to use.
- Not beginner friendly.
- Too many array types.

**Comment by adithyaov** [comment]
The choice is between unecessary copy and memory segementation.

In the beginning, we get pinned arrays
At then end, we have to write unpinned arrays

We need to design the operations inbetween with proper heuristics so we balance
between unecessary copies and memory segmentation.

Or we can have corresponding `*Pinned` combinators or have a `PinnedArray` type
to give more control to the users and let the users chosse.

**Comment by adithyaov** [comment]
Pushing this to `0.11.0`

**Comment by harendra-kumar** [comment]
We have pinned operations in regular array modules now.
