### ISSUE TITLE
TCP acceptor + unfold blocks indefinitely

### ISSUE THREAD

**Issue by agentm** [composewell/streamly#2247]
I've been testing the upcoming streamly 0.9.0 and haven't been able to make a TCP server successfully using 81bfdec2246a38fcda3731289093717f5207d62a on master.

Here's an echo server (adapted from the documented example) which does seem to listen but not accept or respond to incoming data via `nc`:

```haskell
module Test_tcp where
import Control.Exception (finally)
import Network.Socket (Socket, close)
import Data.Function ((&))

import qualified Streamly.Network.Inet.TCP as TCP
import qualified Streamly.Network.Socket as Socket
import qualified Streamly.Data.Stream as Stream
import qualified Streamly.Internal.Data.Stream.Concurrent as Stream -- parMapM is still internal
import qualified Streamly.Data.Fold as Fold

echo :: Socket -> IO ()
echo sk =
      Stream.unfold Socket.reader sk             -- Stream IO Word8
    & Stream.fold (Socket.write sk)

serve :: Socket -> IO ()
serve sk = finally (echo sk) (close sk)

-- | Run a server on port 8091. Accept and handle connections concurrently. The
-- connection handler is "serve" (i.e. lookupWords).  You can use "telnet" or
-- "nc" as a client to try it out.
main :: IO ()
main =
      Stream.unfold TCP.acceptorOnPort 8091 -- Stream IO Socket
    & Stream.parMapM id serve               -- Stream IO ()
    & Stream.fold Fold.drain                -- IO ()
```

```
$ nc -v localhost 8091
Connection to localhost 8091 port [tcp/*] succeeded!
sdf
^C
```

**Comment by adithyaov** [comment]
It's because of the buffer in the `Socket.write` fold.

The doc says this:
```
Write a byte stream to a socket. Accumulates the input in chunks of up to
defaultChunkSize bytes before writing.
```

You can use the `echo` function below instead:
```
echo :: Socket -> IO ()
echo sk =
      Stream.unfold Socket.chunkReaderWith (32768, sk) -- Stream IO (Array Word8)
    & Stream.fold (Socket.writeChunks sk)              -- IO ()
```

Or use `Socket.writeWith` instead of `Socket.write` in the echo function to
specify a smaller chunk size.

See this for the updated example,
https://github.com/composewell/streamly-examples/blob/master/examples/EchoServer.hs

The docs are in the process of getting updated.

Best,
Adithya

**Comment by harendra-kumar** [comment]
@agentm can you confirm, it works for you? Can we close this?

**Comment by agentm** [comment]
I last tested this with a streamly 0.9.0 pre-release. I'll test again with the release and get back to you.

**Comment by agentm** [comment]
I am not able to reproduce this with streamly 0.9.0.
