### ISSUE TITLE
Naming of chunksOf, arraysOf

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2249]
To make the names consistent with other names we could change these to:

* chunksOf => foldChunksOf
* arraysOf => chunksOf

**Comment by adithyaov** [comment]
```
chunksOf => groupsOf
arraysOf => chunksOf
```
But since `chunksOf` is exposed, we need to deprecate it first.
We should rename `arraysOf` to `chunksOf` in the next major release.
