### ISSUE TITLE
Implement the "double" parser in Unicode.Parser

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2275]
* https://hackage.haskell.org/package/attoparsec-0.14.4/docs/src/Data.Attoparsec.Text.html#double
* https://hackage.haskell.org/package/base-4.17.0.0/docs/src/GHC.Read.html#convertFrac

We do not want a dependency on scientific for this.

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/2278
