### ISSUE TITLE
Implement a "Scientific" parser

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2276]
Add it to "streamly" module as the scientific package has non-boot dependencies. Add to Unicode.Parser.Extra module.

**Comment by harendra-kumar** [comment]
Scientific parser can be implemented using the `number` parser easily. We can write a doc example in the documentation of the `number` parser.

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/2461
