### ISSUE TITLE
Streamly version <-> Fully functional GHC versions

### ISSUE THREAD

**Issue by stuser81** [composewell/streamly#2277]
For the current streamly 0.8.3 which GHC versions can be safely used?

Any plans of adding a txt file listing these "Streamly version <-> Fully functional GHC versions"  mappings?

By fully functional I mean: Compiles (obviously) and **no known performance issues compared to other/previous GHCs**.

I'm stuck on GHC 8.10.4 because I'm afraid upgrading might degrade streamly performance.

**Comment by harendra-kumar** [comment]
Do not use >= 9.0.x && < 9.2.2 . Any version >= 9.2.2 should be fine.

**Comment by harendra-kumar** [comment]
This build document has all the info you need on this topic: https://github.com/composewell/streamly/blob/master/docs/User/HowTo/Compiling.md .

**Comment by stuser81** [comment]
Thank you
