### ISSUE TITLE
tee for custom folds

### ISSUE THREAD

**Issue by TimPut** [composewell/streamly#235]
I have two functions which fold a stream down to a single monadic value.
```
f :: SerialT m a -> m b
g :: SerialT m a -> m c
```
I'd like to be able to run both of these functions on the same input stream, and collect the results. Ideally I'd like to write something like the following:
```
h :: SerialT m a -> m (b,c)
h = tee f g
```
I could do this if f and g were folds from Streamly.Fold, but since the Fold constructor is hidden, I can't write custom folds that typematch with FL.tee. *Is there a way to write something like h?*

In my use case, the input to f and g comes from a streaming parser, and each produces an IntMap. I could rewrite f and g into a fold which builds a tuple of maps in the first place, but that seems artificial and unmaintainable.

My current solution is to use Streamly.Prelude.tee with an IORef, approximately like so:
```
main = do
  filename <- fmap head getArgs
  src <- openFile filename ReadMode
  let prs = streamingParser src
  names' <- newIORef IntMap.empty
  graph <- f $ P.tee (\x -> writeIORef names' =<< g x) prs

  deepseq graph (return ())--forces graph, which drains the stream
  names <- readIORef names' --since we've drained the stream, it's now safe to read the IORef
```
This works, and only traverses the input file once, but it now requires that remember to force the result of one fold before reading from the reference for the other fold, which is a little ugly.

**Comment by pranaysashank** [comment]
The `Fold` constructor is exposed via `Streamly.Internal`

**Comment by TimPut** [comment]
I can't believe I missed that. Thank you!

**Comment by harendra-kumar** [comment]
@TimPut the `Fold` constructor is exposed only via` Streamly.Internal` for now because it is going to change in the next release. Once we do that it will be exposed via the `Fold` module itself. It may not be a drastic change though.
