### ISSUE TITLE
Got `undefined` when using direct Stream with parMapM and strict on `State StreamK m a` argument

### ISSUE THREAD

**Issue by TheKK** [composewell/streamly#2423]
Here's how it failed

```haskell
{-# LANGUAGE BangPatterns #-}

import Data.Function ((&))
import qualified Streamly.Data.Stream.Prelude as S
import qualified Streamly.Internal.Data.Stream as D

s :: D.Stream IO ()
s = D.Stream step ()
  where
    step !st () = pure $ D.Stop

go :: IO [()]
go = s & S.parMapM id pure & S.toList
```

and we got exception after running `go`

```
Main > go
*** Exception: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:74:14 in base:GHC.Err
  undefined, called at src/Streamly/Internal/Data/Stream/Concurrent/Channel/Append.hs:114:21 in streamly-0.9.0-915e69518255fbb825b2ec82745814b39d7a07588a939bf78279206e7710156e:Streamly.Internal.Data.Stream.Concurrent.Channel.Append
  ```
  
  I think the `undefined` is from here
https://github.com/composewell/streamly/blob/8fd2b9c81f61bac8daa6b623dfcf563fddfd3267/src/Streamly/Internal/Data/Stream/Concurrent/Channel/Append.hs#L114

Perhaps we could document this requirement (shouldn't force `State` in D.Stream?), since it's not an easy task to figure it out in my case.

**Comment by harendra-kumar** [comment]
This state argument is going to be removed in future. It is not used by the new implementation in 0.9.0 but is retained for backward compatibility, to support the deprecated modules.

**Comment by TheKK** [comment]
Got it! I'll close this issue since we've know it'll be deprecated.
