### ISSUE TITLE
Make ParserK and ParserD consistent

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2459]
ParserK uses negative value for backtracking and positive for forward tracking. ParserD uses positive value for backtracking. We should use the same convention in both to not confuse users writing parsers from scratch. We should change ParserK to conform to ParserD.

**Comment by adithyaov** [comment]
> We should change ParserK to conform to ParserD.

Is this what we've decided? I remember we agreed on ParserK's convention. Or am I mistaken.
If we choose ParserD's convention, there is no way forward tracking anymore.

**Comment by adithyaov** [comment]
Let's use the positive number for backtracking for the following reasons:
1. More common to backtrack and not forward-track
2. Changing ParserD might become more complicated as there are already a lot of users

**Comment by harendra-kumar** [comment]
This is duplicate of #2433  which proposes an opposite solution.

**Comment by harendra-kumar** [comment]
I am closing this in favor of #2433 .
