### ISSUE TITLE
Consistent naming for Unbox module, MutableByteArray

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2539]
MutArray is also a mutable byte array, therefore, it may be better to use RawMutArray instead of `MutableByteArray` to indicate that it is even lower level than MutArray. Also instead of calling the module `Unbox` we can name it based on the type i.e. `RawMutArray`. It can host both `Unbox` and the `Serialize` type classes.

We can also make the API names consistent with the array modules e.g. `newBytes` => `new`.

The names would matter now as we are exposing this functionality for writing Serialize instances.

**Comment by adithyaov** [comment]
We now call it `MytByteArray`. The names have also been changed.
