### ISSUE TITLE
Use resizeMutableByteArray# and shrinkMutableByteArray# to resize MutArray

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2551]
Currently we implement realloc by allocating a new array and copying the old array into it.

**Comment by rnjtranjan** [comment]
As per docs it works for unpinned mutable byte array only. In our code it works for pinned and unpinned both.

**Comment by harendra-kumar** [comment]
We already reuse the old array when we truncate up to a certain threshold, so we can continue using the existing code.
