### ISSUE TITLE
Add mmorph-style operations

### ISSUE THREAD

**Issue by treeowl** [composewell/streamly#256]
I can't guarantee that these are right, but I think they probably make sense.

```haskell
hoistSerialT :: (Monad m, Monad n) => (forall x. m x -> n x) -> SerialT m a -> SerialT n a
hoistSerialT f = embedSerialT (lift . f)

embedSerialT
  :: (Monad m, Monad n)
  => (forall x. m x -> SerialT n x)
  -> SerialT m a -> SerialT n a
embedSerialT f xs =
  (f $ SP.uncons xs) >>= \case
    Nothing -> nil
    Just (a, as) -> yield a <> embedSerialT f as
```

I'm not sure whether access to the internals would allow the looser constraints needed for instances of `MFunctor` and `MMonad`.

**Comment by pranaysashank** [comment]
I don't think it is possible to write an instance for MFunctor, we need a Monad constraint on the transformed stream as well. However we can provide similar functions to hoist, implemented internally, from Streamly.Prelude in future releases. #79

**Comment by harendra-kumar** [comment]
@treeowl your hoist code looks good to me. I tried putting your code in StreamK.hs and make it polymorphic, like so:

```
embed
  :: (IsStream t, Monad m, Monad n, Monad (t n))
  => (forall x. m x -> t n x) -> t m a -> t n a
embed f = go
    where
    go xs = do
        r <- f $ uncons xs
        case r of
            Nothing -> nil
            Just (a, as) -> a `cons` embed f as

hoist :: (IsStream t, Monad m, Monad n, MonadTrans t, Monad (t n))
    => (forall x. m x -> n x) -> t m a -> t n a
hoist f = embed (lift . f)
```

We can export it through the `Streamly.Internal` module for now, that's where we keep experimental APIs which can potentially be included in future releases. We will be happy to accept a PR if you feel like raising one.

We can also add a benchmark to see how it performs. We can add a simple benchmark hoisting to Identity in `benchmark/LinearOps.hs/Linear.hs`. Like we have for `foldrT` which switches only the transformer monad.

**Comment by treeowl** [comment]
I don't know much about `streamly` yet. Vague intuition suggests that for `SerialT` these will work for any natural transformation, but that for at least some of the others they only make sense for monad morphisms. Is that right? If so, I'll need to document that.

**Comment by pranaysashank** [comment]
@harendra-kumar We can do a simpler direct implementation instead of using uncons, but we'd need to internally have a hoist function for State `State Stream m a -> State Stream n a`. Once we have that, we can do
```
hoist :: (IsStream t, Monad m, Monad n) => (forall x. m x -> n x) -> t m a -> t n a                                                 
hoist f str =                                                                                                                       
    mkStream $ \st yld sng stp ->                                                                                                 
            let single = return . sng                                                                                             
                yieldk a s = return $ yld a (hoe f s)                                                                             
                stop = return stp
                state = hoistState (return . f) st                                                                                                 
             in join . f $ foldStreamShared state yieldk single stop str
```

**Comment by harendra-kumar** [comment]
@pranaysashank  this looks good! This is likely to perform better than the `uncons` version. We can perhaps benchmark both implementations to see the difference.

Why can't we just adapt the state simply like this:

```
adaptStateX :: State t m a -> State t n b
adaptStateX st = st
    { streamVar = Nothing
    , _yieldLimit = Nothing
    }
```

**Comment by pranaysashank** [comment]
Yes, of course!! That should work, we can perhaps even make the function signatures more general on the existing `adaptState`.

```Haskell
> delay n = threadDelay (n * 1000000) >> print n >> return n
> p = delay 3 |: delay 2 |: delay 1 |: S.nil
> runIdentityT $ S.toList $ S.hoist IdentityT (parallely p)
1
2
3
[1,2,3]
```

We should also test for stateful monads to see it does the proper thing.

**Comment by treeowl** [comment]
I don't know if it makes a difference for implementation here, but to the
extent that we can make things work sensibly when passed functions that
aren't monad morphisms, I think we should. That can be quite useful.

**Comment by harendra-kumar** [comment]
@treeowl yes that's true especially since we cannot automatically check/enforce if a function is a monad morphism or not.

**Comment by treeowl** [comment]
If there's an efficiency benefit to an "unsafe" version, we can of course
offer both.

**Comment by hasufell** [comment]
Awesome, we're already using the version from @harendra-kumar in our code. Had to add `adapt` after uncons though: `r <- f $ S.uncons (adapt xs)`

Another thing I was wondering is... if there was a way to have a different output value than `a`. Imagine the hoist is running runExceptT for example and you want to wrap the value in an Either thus. Does that even make sense in context of streamly?

**Comment by harendra-kumar** [comment]
> if there was a way to have a different output value than a. 

Please help me understand this. How does your whole pipeline look like? I assume you run ExceptT after running the stream? In that case it will return an Either value in its base monad.

**Comment by harendra-kumar** [comment]
@treeowl @pranaysashank I added `hoist` in #302 . Please take a look. This is still in an Internal module, but Internal modules are exposed, so can be used immediately.

**Comment by harendra-kumar** [comment]
We now have the basic operations in prelude. Closing this.
