### ISSUE TITLE
Release with GHC 9.6 support

### ISSUE THREAD

**Issue by georgefst** [composewell/streamly#2597]
The current `HEAD` builds with `ghc-9.6.3`, but the latest Hackage version does not. It requires `--allow-newer='streamly:ghc-prim,streamly-core:ghc-prim,streamly-core:template-haskell'` to get the build started, then fails at `src/Streamly/Internal/Control/Concurrent.hs:54:15`. Since this issue must have since been fixed, could we please get a new Hackage release with this patch?

**Comment by metaml** [comment]
Yes, please release an official version for ghc 9.6.x. I'm on 9.6.3 and using streamly-core without any issues. Thanks!

**Comment by harendra-kumar** [comment]
We will plan to release 0.10.0 in next 2 weeks.

**Comment by recursion-ninja** [comment]
Any update on the release timeline?

**Comment by harendra-kumar** [comment]
Likely to be released this week or early next week.

**Comment by harendra-kumar** [comment]
Candidates uploaded for [streamly-core-0.2.0](https://hackage.haskell.org/package/streamly-core-0.2.0/candidate) and [streamly-0.10.0](https://hackage.haskell.org/package/streamly-0.10.0/candidate). Will wait for a day before publishing. Sorry for the delay.
