### ISSUE TITLE
Consolidate encodeConstrNames and encodeRecordFields options into a single option

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2630]

**Comment by adithyaov** [comment]
How will this work? These are two distinct options.

**Comment by adithyaov** [comment]
TODO: Write an example for why these options need to be distinct before closing this issue.

**Comment by adithyaov** [comment]
Consider,
```
data Record = A { f :: Int } | B { g :: String }
```

On `encode (A 1)`,

Without any options: `"01"`
With `encodeConstrNames`: `"A1"`
With `encodeRecordFields`: `"Af1"`
