### ISSUE TITLE
Rename "toFold" from the Parser module to unsafeToFold

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2717]
This is a partial function as folds are less powerful than parsers, not all parsers can be safely converted to folds. However, folds converted to parsers can be safely converted back to folds.

**Comment by adithyaov** [comment]
Should we expose `unsafeToFold` I use it quite often when dealing with parsers.

**Comment by adithyaov** [comment]
The use of word `unsafe` is not required here. This is a partial function, just like `head`.
Making all partial functions `unsafe` , removes the credibility of the `unsafe` keyword.
