### ISSUE TITLE
Add Pipes.Lift-style functions

### ISSUE THREAD

**Issue by treeowl** [composewell/streamly#272]
For example,

```haskell
import Control.Monad.State.Strict

evalStateStreamly :: forall m s a. Monad m => s -> SerialT (StateT s m) a -> SerialT m a
evalStateStreamly s str = do
  (m, s') <- yieldM $ runStateT (uncons str :: StateT s m (Maybe (a, SerialT (StateT s m) a))) s
  case m of
    Nothing -> nil
    Just (a, more) -> S.cons a $ evalStateStreamly s' more
```

I don't know if it's possible to get any faster. This particular one isn't very parallelizable (a thread can't actually *use* the initial state it's handed until it's been calculated), but I expect some others (`ReaderT`, for sure, and likely `WriterT`) are.

**Comment by treeowl** [comment]
`runReaderStreamly` is a simple application of `hoist`, discussed in #256.

**Comment by treeowl** [comment]
Pretty sure `WriterT` should work too, with some applications preserving the accumulation order and others not.

**Comment by harendra-kumar** [comment]
@treeowl thanks for the implementation. Running a stream with a state could be quite useful in general, its on my mind. We will focus more on this area after releasing 0.7.0. We will add benchmarks to measure the performance. I would perhaps express these combinators using the direct style stream implementation (`Streamly/Streams/StreamD.hs`) for better performance with fusion.

**Comment by harendra-kumar** [comment]
Please see #302. I have added support for running `StateT` and `ReaderT` in parts of stream. I have implemented those using the direct style stream instead of CPS. Its very fast as everything fuses. There seems to be almost no overhead of state or reader.

**Comment by harendra-kumar** [comment]
StateT and readerT are already implemented. We can open a new issue if writerT is needed.
