### ISSUE TITLE
In the FileSystem.Event module replace "Array Word8" with Path

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2766]
We can deprecate the original module and have the modified APIs in a new `FileSystem.Notify` or `FileSystem.Watch` module.

**Comment by harendra-kumar** [comment]
Instead of changing anything in the existing internal modules let's do this:

* Create a new streamly-fsevents package with including the FileSystem.Event modules
* Deprecate these modules in the streamly package

**Comment by georgefst** [comment]
> Create a new `streamly-fsevents` package

FYI, I do already maintain a small similar package, but I'd be happy to deprecate it if your version makes it obsolete. I'm not particularly attached to this code. I just inherited it when the original author gave up.

https://github.com/georgefst/streamly-fsnotify/issues/5
