### ISSUE TITLE
Expose the FileSystem.Path module

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2767]
The internal Streamly.Internal.FileSystem.Path module needs to be exposed via Streamly.FileSystem.Path module. We can skip exposing the Typed path modules for now. Just the basic Path module should be enough for this release. The FileSystem.File/Dir/Event modules depend on this change.

**Comment by adithyaov** [comment]
Let's also expose Typed modules.

**Comment by adithyaov** [comment]
See: https://github.com/composewell/streamly/pull/2780
