### ISSUE TITLE
Expose scan running functions

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2791]
`Fold.runScan` and `Stream.runScan`.

**Comment by adithyaov** [comment]
We need to deprecate the `scan*` and `postscan*` functions. 
We shouldn't encourage `Fold` to scan anymore, rather, we should use `Scan`.

**Comment by adithyaov** [comment]
This issue is obsolete. Scans have evolved since the issue.
See: https://github.com/composewell/streamly/issues/2846
