### ISSUE TITLE
Make deserialize in Data.Array similar to the one in MutArray

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2802]
To deserialize piecemeal. If an Array has multiple objects we should be able to deserialize them one at a time.

**Comment by adithyaov** [comment]
Should we remove `serialize` in `Data.Array`?
`serialize` and `deserialize` won't look like duals if `Array.deserialize` looks like `MutArray.deserialize` but `Array.serialize` looks different from `MutArray.serialize`.

**Comment by adithyaov** [comment]
We can rename `Array.serialize` to `encode`

**Comment by adithyaov** [comment]
Or we can keep it as it is.
