### ISSUE TITLE
Issue of multithreading with Parallely on new version ? 

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#281]
On the version pointing on this commit : 4810c8eef66a45aadfbea0497aa82389d97160bc, I have the following issue : 
```
S.drain
  $ S.mapM (\actionIndex -> log logger INFO $ "action index : " ++ show actionIndex)
  $ S.parallely
  $ S.fromList [(1::Integer)..10]
```
gives me the following behaviour : 

```
ThreadId 11 - action index : 1
ThreadId 11 - action index : 2
ThreadId 11 - action index : 3
ThreadId 11 - action index : 4
ThreadId 11 - action index : 5
ThreadId 11 - action index : 6
ThreadId 11 - action index : 7
ThreadId 11 - action index : 8
ThreadId 11 - action index : 9
ThreadId 11 - action index : 10
```
This is only on one thread ? Is it normal ? I was expecting having each log on a different one..

**Comment by harendra-kumar** [comment]
You are applying `parallely` only to `fromList`, apply it before `mapM` instead to get the expected output:

```
S.drain
  $ S.parallely
  $ S.mapM (\actionIndex -> log logger INFO $ "action index : " ++ show actionIndex)
  $ S.fromList [(1::Integer)..10]
```

**Comment by nhenin** [comment]
The way I though I understood `parallely` was an equivalent to `fan out` : 
```
source (fromList) > parallely (fan out items)  > mapM on each item dispatched on a different thread
```
How should I understand : `applying parallely only to fromList`, it looks like I'm missing something fundamental here...

**Comment by adithyaov** [comment]
@nhenin I don't think `parallely` and `fan out` are equivalant. I might be wrong but according to my understanding, `parallely`, `serially`, etc. are more like runners and the inner stream functions `mapM`, etc. are like composers.
Note that, `S.mapM` does not apply the functions but fuses the function into the corresponding stream. So if you think about `parallely` as running a stream of computations in parallel, you first perform `S.mapM` to extend the computation and run the computations in parallal using `parallely`

**Comment by nhenin** [comment]
how can run each log concurrently on that example ? 
```
S.drain
      $ S.concatMapM (\x ->
          return $ S.asyncly
          $ S.mapM (\y -> log logger INFO $ "(" ++ show x ++ ","++ show y ++ ")" )
          $ S.fromList [(10::Integer)..20])
      $ S.asyncly
      $ S.fromListM (return <$> [(1::Integer)..10])
``
it does it for `y` but not for `x` : 
```
cli-client-simulator] - ThreadId 22 - (1,10)
[cli-client-simulator] - ThreadId 23 - (1,11)
[cli-client-simulator] - ThreadId 24 - (1,12)
[cli-client-simulator] - ThreadId 25 - (1,13)
[cli-client-simulator] - ThreadId 26 - (1,14)
[cli-client-simulator] - ThreadId 27 - (1,15)
[cli-client-simulator] - ThreadId 28 - (1,16)
[cli-client-simulator] - ThreadId 29 - (1,17)
[cli-client-simulator] - ThreadId 30 - (1,18)
[cli-client-simulator] - ThreadId 31 - (1,19)
[cli-client-simulator] - ThreadId 32 - (1,20)
[cli-client-simulator] - ThreadId 36 - (2,10)
[cli-client-simulator] - ThreadId 37 - (2,11)
[cli-client-simulator] - ThreadId 38 - (2,12)
[cli-client-simulator] - ThreadId 39 - (2,13)
[cli-client-simulator] - ThreadId 40 - (2,14)
[cli-client-simulator] - ThreadId 41 - (2,15)
[cli-client-simulator] - ThreadId 42 - (2,16)
[cli-client-simulator] - ThreadId 43 - (2,17)
[cli-client-simulator] - ThreadId 44 - (2,18)
[cli-client-simulator] - ThreadId 45 - (2,19)
[cli-client-simulator] - ThreadId 47 - (2,20)
[cli-client-simulator] - ThreadId 50 - (3,10)
[cli-client-simulator] - ThreadId 52 - (3,11)
[cli-client-simulator] - ThreadId 55 - (3,12)
```

**Comment by nhenin** [comment]
ok I'm on the right path I think : -- concatMap = 'concatMapWith' 'Serial.serial'

**Comment by harendra-kumar** [comment]
It is correct that most monadic functions are concurrent and pure functions are not. Currently `concatMapM` is an exception, it is monadic but not concurrent. The concurrent version of concatMap is `concatMapWith`.

**Comment by nhenin** [comment]
can we do a concatMapWith with parallel ? I'm trying to figure our now...

**Comment by harendra-kumar** [comment]
Yes you can use `parallel` as long as the stream is not infinite. See this https://github.com/composewell/streamly/blob/master/examples/FileSinkServer.hs for an example.

**Comment by nhenin** [comment]
I'm having this use case in our project everywhere.... I have an issue then...

**Comment by harendra-kumar** [comment]
What is the issue?

**Comment by nhenin** [comment]
I'm working with infinite streams and concatMapping them

**Comment by nhenin** [comment]
what is the issue with concatMapping inifinite streams together ?

**Comment by nhenin** [comment]
Sorry ... I want the equivalent of a merge...

**Comment by harendra-kumar** [comment]
The semantics of parallel are such that each task composed in parallel will run concurrently, therefore, running it on infinite stream would mean running infinite number of tasks concurrently. Note that the stream can be infinite as long as the tasks running concurrently at a time are finite.

A better alternative would be to use `async` instead of `parallel`, async can run safely on infinite streams. The difference is that in case of `async` new tasks may wait until more room is created when earlier tasks finish. You can use `maxThreads` and `maxBuffer` combinators to control how many tasks you want to run concurrently. In case of `parallel` max threads is unlimited.

**Comment by harendra-kumar** [comment]
You can also use merge combinators with `concatMapWith` e.g. something like `concatMapWith (mergeAsyncBy f)` should merge the generated streams concurrently.

**Comment by nhenin** [comment]
It is doing what I wanted I guess, I could play with `maxThreads` eventually...
```
S.drain
      $ S.concatMapWith S.async
        (\x ->
          S.asyncly
          $ S.mapM (\y -> log logger INFO $ "(" ++ show x ++ ","++ show y ++ ")" )
          $ S.fromList [(10::Integer)..])
      $ S.fromList  [(1::Integer)..]
```
I'll look at `mergeAsyncBy f` also ! thanks @harendra-kumar  and @adithyaov for your help !
