### ISSUE TITLE
Streamly doesn't build with Stack on Mac OS 

### ISSUE THREAD

**Issue by AliceRixte** [composewell/streamly#2833]
I've been using Streamly on Windows with a project I build using `stack build`. It works great and this is an amazing library, thank you so much for this work 🎉 !

However, I just tried to build my project on Mac OS Sonoma 14.4.1 (with an Apple M2 chip) and the build fails with the following error :

```
streamly    > <<ghc: 124151944520 bytes, 2919 GCs, 119349929/206603200 avg/max bytes residency (44 samples), 574M in use, 0.001 INIT (0.001 elapsed), 60.617 MUT (97.917 elapsed), 23.990 GC (24.379 elapsed) :ghc>>

streamly    > ar: .stack-work/dist/aarch64-osx/ghc-9.8.2/build/src/Streamly/Internal/FileSystem/Event/Darwin.o: No such file or directory
```

I'm using stack's nightly resolver as I need a bugfix from another library, and I have the above error both with 

`resolver: nightly-2024-06-20`

and today's resolver :

`resolver: nightly-2024-09-18`

I'm building with the following dependency constraint : 

`- streamly >= 0.10.1`

How can I build streamly on Mac OS ?

**Comment by harendra-kumar** [comment]
Are you able to build it with `cabal build`?

Also, in the stack output, there may be some other error message above the one you pasted. There may have been an error during the compilation of src/Streamly/Internal/FileSystem/Event/Darwin.hs because of which Darwin.o was not generated. Can you find any other such error messages, if present and paste those as well here?

One possibility is that you do not have the Cocoa framework installed in your mac for some reason or stack/ghc is not able to find it.

We do have macOS CIs which are passing, but have to check if those are running on intel or arm.

**Comment by AliceRixte** [comment]
Thank you for your answer ! 

Darwin.hs does compile, it yields a warning which does not look related to the issue : 

```
streamly        > [64 of 72] Compiling Streamly.Internal.FileSystem.Event.Darwin
streamly        >     
streamly        > /private/var/folders/5v/_ynr_bm92_58nz2tslysw1480000gn/T/stack-4e48c2bb4cb197fb/streamly-0.10.1/src/Streamly/Internal/FileSystem/Event/Darwin.hs:1039:65: warning: [GHC-68441] [-Wdeprecations]
streamly        >     In the use of ‘toStream’
streamly        >     (imported from Streamly.Internal.Data.Array, but defined in Streamly.Internal.Data.Array.Type):
streamly        >     Deprecated: "Please use 'read' instead."
streamly        >      |
streamly        > 1039 |     let path = runIdentity $ S.fold FL.toList $ U.decodeUtf8' $ A.toStream eventAbsPath
streamly        >      |                                                                 ^^^^^^^^^^
streamly        > [65 of 72] Compiling Streamly.Internal.FileSystem.Event
```

**Comment by AliceRixte** [comment]
For now, `cabal build` is broken for other reasons not linked to `streamly`.

I tried to "install" cocoa, but I have to admit I don't know how to. It looks like I'd have to use XCode and that this is an Objective-C framework, but I have no idea how I can "link" this frame work to cabal or stack.

Every resource mentioning Cocoa on google are related to XCode and Objective C. Am I missing something ?

**Comment by harendra-kumar** [comment]
Glad to know it compiles with cabal.

**Comment by AliceRixte** [comment]
The thing is : I really prefer working with stack. Do you plan to fix this or should I completely switch back from stack to cabal (which is fine, even if I'd rather not to) if I want to use streamly ?

**Comment by harendra-kumar** [comment]
There is a stack CI [here](https://github.com/composewell/streamly/blob/8370ec315d019ed55c0696f4e40e7ec500a24e3e/.github/workflows/haskell.yml#L190) . If you can send a PR adding another CI by copying this, changing the config to your compiler and stack-snapshot then we can play with it and get it working.
