### ISSUE TITLE
Can't access the drain function

### ISSUE THREAD

**Issue by walseb** [composewell/streamly#284]
Hi! I'm trying to get an example to work and it uses `drain` from `Streamly.Prelude` but however I install streamly (through nix, stack or cabal. 0.5.2 or latest version) it is never usable even though it's clearly exported in the source code. This reproduces the problem on my machine atleast
```
mkdir test
cd test
stack new test
stack install streamly
stack repl
:browse Streamly.Prelude
```
Now the drain command isn't in the output of `ghci` command.
Thanks for any help!

**Comment by pranaysashank** [comment]
The version on Hackage doesn't have `drain` implemented. The master branch on this repo is ahead of the Hackage version, you can use the package directly from github until a new version is released

**Comment by walseb** [comment]
Ah I see thanks!
