### ISSUE TITLE
ThreadAbort Exception Raised

### ISSUE THREAD

**Issue by nhenin** [composewell/streamly#286]
I have some ThreadAbort Exceptions raised when I'm stressing my streams too much, can you give us more information on the reasons why this could happen ?

**Comment by harendra-kumar** [comment]
In a concurrent composition you could have several producer threads and a consumer thread consuming their outputs. If the consumer thread terminates before the producers have finished then a `ThreadAbort` exception is thrown to the producers to clean them up. 

Can you provide more details on the problem you are facing? What is the symptom that you are seeing? Can you paste the output if any? Is it affecting the functionality or is it just some extra noise output?

You can also use `inspectMode` to get more debugging details. This combinator is available in `Streamly.Internal.Prelude` module on the master branch or in `Streamly.Internal` module in the released versions.
