### ISSUE TITLE
Change the Replace constructor argument order

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#2883]
In incremental folds:

```
data Incr a =
      Insert !a
    | Replace !a !a -- ^ Replace new old
```

`Replace old new` may read better as "replace old by new".

**Comment by adithyaov** [comment]
Both make sense to me depending on the picture of how a window looks in my mind.
`Insert new and Evict old` vs `Replace old by new`

**Comment by adithyaov** [comment]
Need to also change it in,
- streamly-indicators
- streamly-statistics

**Comment by adithyaov** [comment]
Check if the intuition is proper. Look at a few combinators and check.
