### ISSUE TITLE
Unpinned array implementation

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#297]
The array implementation in `Streamly.Memory.Array`  uses pinned memory, pinned memory is needed for interfacing with the OS. In many cases unpinned arrays may perform better than pinned, especially when we have short and short lived data. We should have an unpinned array implementation in `Streamly.Data.Array`. This will be just a replication of current implementation except that we will be using a `ByteArray#` for the array implementation instead of a `ForeignPtr`.

we can potentially use `PrimArray` (http://hackage.haskell.org/package/primitive-0.7.0.0/docs/Data-Primitive-PrimArray.html) from the `primitive` package for this implementation.

**Comment by adithyaov** [comment]
Implemented in #379

**Comment by pranaysashank** [comment]
Reopening the issue as `Streamly.Data.Array` is not exposed.

**Comment by harendra-kumar** [comment]
Unpinned arrays are now available in 0.9.0 .
