### ISSUE TITLE
Can streamly do file watching efficiently?

### ISSUE THREAD

**Issue by kozross** [composewell/streamly#318]
I've tried to implement this myself, but when watching 25 files, I get severe CPU use and ever-increasing RAM load. I don't know if this is me doing it wrong - is this something streamly is conceptually suitable for, and if so, how would I do it?

**Comment by harendra-kumar** [comment]
Do you have the code uploaded somewhere where I can see it? Or maybe share some snippet here?

**Comment by kozross** [comment]
The thing I use to watch one file:

```haskell
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE ScopedTypeVariables #-}

module System.Observer where

import Data.Kind (Type)
import Data.Time.Clock (UTCTime)
import Streamly (WAsyncT, MonadAsync)
import System.Directory (getModificationTime)
import Control.Exception (try, IOException)
import Control.Concurrent (threadDelay)
import Control.Monad.IO.Class (liftIO)

-- What state the file is in - either it's missing, or it's been updated
data FileState = NotThere | LastUpdated UTCTime
    deriving (Eq)

rate :: Int
rate = 500000

fileStatus :: forall (m :: Type -> Type) . 
    (MonadAsync m) =>
    FilePath -> WAsyncT m FileState
fileStatus fp = S.repeatM (liftIO . (threadDelay rate *>) . fmap (either (const NotThere) LastUpdated) . try @IOException . getModificationTime $fp)
```

The way I execute all this (minus database interaction code, in a different module):

```haskell
-- bunch of unrelated imports
import Streamly (adapt)

import qualified Streamly.Prelude as S

import System.Observer (FileState(..), fileStatus)

-- main can be assumed to first do a bunch of database calls to get the list
main :: IO ()
main = do panopticon <- fmap (mconcat . fmap fileStatus) listOfFilePathsToWatchFromDatabase
          liftIO . S.drain . adapt . S.mapM printFileState $ panopticon
  where printFileState NotThere = pure () -- do nothing
        printFileState (LastUpdated t) = putStrLn ("Saw change: " ++ show t)
```

**Comment by pranaysashank** [comment]
I tried the above code with a static list of 34 filepaths and I am getting a constant 2% memory usage and a variable cpu load (0.2-12%). 

Can you reproduce the issue with the code you pasted above (i.e. without the database code)? 
Also, what version of ghc and streamly are you using?

**Comment by harendra-kumar** [comment]
This is a brute force approach for file watching and can be very inefficient. The performance may depend on the filesystem/storage media used because we are always reading the metadata for each file in question periodically.

The ideal way to watch files is using inotify. See http://hackage.haskell.org/package/hinotify and  http://hackage.haskell.org/package/hfsevents . There are also high level packages available e.g. http://hackage.haskell.org/package/fsnotify .

Streamly can potentially natively support a stream of file watch events based on inotify, but it is not yet there.

**Comment by kozross** [comment]
@harendra-kumar I'm on Windows, which means inotify-based approaches aren't possible. ``fsnotify`` might work, but I have no idea how I would use this with streamly.

**Comment by pranaysashank** [comment]
No, I am not on windows. I am on macOS (Catalina), also not sure why the underlying file system would cause ever increasing RAM load since everything in here should be bounded and at any point of time we would only be doing a bounded number of system calls.

**Comment by harendra-kumar** [comment]
@kozross this approach should also work pretty well though not as efficiently as inotify.  Are you using the latest streamly version i.e. 0.7.0?

We want to generate the status events for individual files serially and not concurrently. Your `repeatM` is of type WAsyncT and therefore it would generate events concurrently for the same file, that will create a storm of events. Instead use it like this:

```
fileStatus fp = serially $ S.repeatM ...
```

Alternatively, you can make the type of `fileStatus`  `SerialT` and instead of using `mconcat` use `foldWith wAsync` to merge the streams after the `fmap`. `foldWith` and `wAsync` are in the `Streamly` module.

Let us know if that fixes the problem.

**Comment by kozross** [comment]
@harendra-kumar Following your advice, I found that ``fsnotify`` has something close to what I need, though not quite ideally so. I came up with the following solution:

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

module System.Observer where

import Data.Time.Clock (UTCTime, getCurrentTime)
import Streamly (SerialT, constRate)
import System.FSNotify (WatchManager, StopListening, startManager)
import System.FSNotify.Devel (treeExtExists)
import Control.Concurrent.Chan (newChan, writeChan, readChan)

import qualified Streamly.Prelude as S

watchForExes :: FilePath -> IO (WatchManager, StopListening, SerialT IO (FilePath, UTCTime))
watchForExes dir = do man <- startManager
                      chan <- newChan
                      stop <- treeExtExists man dir ".exe" (placeWithTime chan)
                      let stream = constRate 5.0 . S.repeatM $ readChan chan
                      pure (man, stop, stream)
  where placeWithTime chan fp = do t <- getCurrentTime
                                   writeChan chan (fp, t)
```

This works like a charm - no CPU burn or heavy RAM loads. Unfortunately, ``treeExtExists`` takes something of type ``FilePath -> IO ()`` for its callback, which forces my use of a ``Chan`` and a monomorphic-to-IO effect in the resulting stream. Is this the right approach in such a case? Is there a way I could make this work in ``MonadAsync m`` instead?

**Comment by harendra-kumar** [comment]
Looks good. If you want to keep the monad polymorphic in the stream, you can use `S.repeatM $ liftIO $ readChan chan`.  In future we will try to incorporate the inotify functionality natively in streamly, that will make the solution more elegant.

**Comment by kozross** [comment]
I've decided to generalize and package up my work on this - it can now be found as [``streamly-fsnotify``][1].

[1]: http://hackage.haskell.org/package/streamly-fsnotify-1.0.0.0

**Comment by harendra-kumar** [comment]
That looks cool @kozross ! Good work. Though a more permissive license would enable better adoption of the library.
