### ISSUE TITLE
Equivalent code producing different output

### ISSUE THREAD

**Issue by hussein-aitlahcen** [composewell/streamly#34]
I have found that two equivalent codes are producing different output.
* the first **flow** will produce `[(1, 1), (2, 2), (3, 3)]`
* while **the second** one will produce a single tuple `[(1, 1)]`

Maybe I am stupid but I can't find the answer to this behavior... ?

Example:
```haskell
import           Control.Monad    (join)
import           Streamly
import qualified Streamly.Prelude as S

main = mapM_ print $ join (S.toList . zipping $ flow)
  where
    flow = (,) <$> stream <*> stream
    -- flow = pure (,) <*> stream <*> stream
    stream = S.each [1, 2, 3]
```

**Comment by harendra-kumar** [comment]
@hussein-aitlahcen thanks for reporting. This is a bug! The implementation of `pure` in `ZipStream` is incorrect. Currently it just puts a single value in the stream, instead, it should be repeating the value forever like this:

```
    pure a = ZipStream $ let x = scons a (Just x) in x
```

It will take me at least one more day to get back to fixing it, unless you want to take a stab at it. It will need adding a failing test case in `test/Main.hs` and fixing the `ZipStream` applicative instance to make it pass, that's it.

**Comment by harendra-kumar** [comment]
`ZipAsync` will require a similar fix.

**Comment by hussein-aitlahcen** [comment]
@harendra-kumar fix done I guess
