### ISSUE TITLE
Finalization when the stream is not fully evaluated

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#370]
`after`, `finally`, and `bracket` combinators attach an action with a stream which is run if the stream stops normally or due to an exception. However, if the stream is lazily evaluated using a right fold and the fold terminates without fully evaluating the stream, the finalization action may never be invoked. This can cause confusing behavior.

One possible solution could be to bracket/finalize folds rather than bracketing/finalizing streams and unfolds.

**Comment by harendra-kumar** [comment]
Thanks @hasufell for reporting this issue.

**Comment by harendra-kumar** [comment]
Fixed by #372

**Comment by pranaysashank** [comment]
Reopening this issue as these are only exposed from Internal modules in 0.7.1

**Comment by harendra-kumar** [comment]
This is fixed in released code now.
