### ISSUE TITLE
Change the signature of foldrM

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#38]
The current signature is different from the standard `foldrM` in Foldable. We can implement it like this:

```
{-# INLINE foldrM #-}
foldrM :: (Streaming t, Monad m) => (a -> b -> m b) -> b -> t m a -> m b
foldrM consume final m = go (toStream m)
    where
    go m1 =
        let stop = return final
            yield a Nothing  = consume a final
            yield a (Just x) = go x >>= consume a
         in (runStream m1) Nothing stop yield
```

The toList implementation will then become:

```
toList = foldrM (\a xs -> return $ a : xs) []
```

It also improves the performance of `toList` by 10%.

**Comment by Abhiroop** [comment]
For reference of others there is an open PR for this here: https://github.com/composewell/streamly/pull/40

**Comment by harendra-kumar** [comment]
Note: commit 0ce4a6d5adbce5673d820817b2493d52bfa29fbe changed the signature back to the original because the new signature made foldrM unnecessarily strict.
