### ISSUE TITLE
Basic questions:

### ISSUE THREAD

**Issue by ghost** [composewell/streamly#395]
* Is streamly production ready?
* Are there any currently known bugs that could cause problems on production systems?
* What's the exception handling / resource allocation story on streamly? How do you close file handles, cleanup, etc. when exceptions occur? Crucial in production.

**Comment by harendra-kumar** [comment]
> Is streamly production ready?

The core functionality is ready. We are continuously improving things, it may be a good idea to take a look at the changelog for some history.  There are still many things to do. One important thing that we have in the immediate roadmap is stream parsing. Though you can very well use existing parsers like attoparsec with streamly. There are a large number of tests and benchmarks, almost every exposed combinator is covered by tests and benchmarks. Several  commercial users are using the library in production.

> Are there any currently known bugs that could cause problems on production systems?

Some bugs were fixed recently, see the changelog. A new minor release is coming soon. All known bugs have issues labeled "bug". There are no known serious yet not fixed bugs. There is commercial support available if you need SLAs on bug fixing or feature implementations.

> What's the exception handling / resource allocation story on streamly?

The standard `bracket`, `handle`, `finally` combinators for streams are available in `Streamly.Prelude`.  For lazy evaluation case the cleanup action is invoked by GC. A resource-t style approach can also be used for prompt cleanup but we are exploring the design space whether we really need prompt cleanup and if so what is the best way to do it in the context of streamly.

**Comment by harendra-kumar** [comment]
https://github.com/juspay is using Haskell/Streamly in production.

**Comment by hydramo** [comment]
> A resource-t style approach can also be used for prompt cleanup

Is this being used by anyone in the open yet? It seems the most common approach is MonadResource but this seems incompatible with MonadAsync. Are there known alternatives?

**Comment by harendra-kumar** [comment]
I know some folks were using the resource-t version prior to the unliftio change.

**Comment by hydramo** [comment]
I'm asking on their issues why they'd do such a thing. The problem was already solved, but someone pulled the rug out from under us and "unsolved" it.

**Comment by harendra-kumar** [comment]
We should be grateful to the authors of the package. Of course the authors have the privilege to decide the direction of the package, and whatever the change is it is usually for good reasons. We can always reuse the work and fork the package for conflicting use cases if needed.

**Comment by slotThe** [comment]
> Though you can very well use existing parsers like attoparsec with streamly. 

This might be a rather basic question, but how would one do this?  Say one had a rather long text file one wished to read and parse with some attoparsec parser for `ByteString` (or `Text`, I suppose).

**Comment by harendra-kumar** [comment]
@slotThe take a look at the [attoparsec docs](http://hackage.haskell.org/package/attoparsec-0.13.2.3/docs/Data-Attoparsec-ByteString.html), it can take incremental input. So you can [read a stream of bytestrings](http://hackage.haskell.org/package/streamly-bytestring-0.1.0.1/docs/Streamly-External-ByteString.html) and feed the chunks incrementally to an attoparsec parser using a fold or scan.

**Comment by slotThe** [comment]
Worked like a charm, thank you so much!


Feb 9, 2020, 08:39 by notifications@github.com:

**Comment by harendra-kumar** [comment]
@hydramo looks like it is not difficult to write a `runResourceT` using `MonadBaseControl`:

```
{-# LANGUAGE FlexibleContexts #-}

module RunResourceT where

import Control.Exception (catch, mask, throwIO)
import Control.Monad.IO.Unlift (MonadIO(..), MonadUnliftIO, withRunInIO)
import Control.Monad.Trans.Control (MonadBaseControl, control)
import Control.Monad.Trans.Resource (createInternalState)
import Control.Monad.Trans.Resource.Internal
       (ResourceT(..), stateCleanupChecked)

runResourceT :: MonadBaseControl IO m => ResourceT m a -> m a
runResourceT (ResourceT r) = control $ \run -> do
    istate <- createInternalState
    mask $ \restore -> do
        res <- restore (run (r istate)) `catch` \e -> do
            stateCleanupChecked (Just e) istate
            throwIO e
        stateCleanupChecked Nothing istate
        return res
```

You can use this function instead of the runResourceT in the resourcet package and use the regular resourcet package. Rest of the functionality you can take from resourcet package. I have not tested it though.

**Comment by stuser81** [comment]
> @slotThe take a look at the [attoparsec docs](http://hackage.haskell.org/package/attoparsec-0.13.2.3/docs/Data-Attoparsec-ByteString.html), it can take incremental input. So you can [read a stream of bytestrings](http://hackage.haskell.org/package/streamly-bytestring-0.1.0.1/docs/Streamly-External-ByteString.html) and feed the chunks incrementally to an attoparsec parser using a fold or scan.

@slotThe @harendra-kumar This is exactly what I had in mind here: https://github.com/composewell/streamly/issues/1139

The question is, if we can already use existing parsing libraries (already tried and tested for years / decades) with streamly, why was it seen as necessary for streamly to have its own parser? (Asking out of curiosity)

**Comment by harendra-kumar** [comment]
@stuser81 I answered your question in #1139 .
