### ISSUE TITLE
Add a catMaybe combinator

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#430]
To filter extract `Just` values from a `Maybe` stream and remove the `Just` wrapper. Though it would be just`catMaybe = mapMaybe id`, its perhaps better to have the `catMaybe` combinator as it is easier to remember than the `mapMaybe id` idiom, especially for newbies.

**Comment by rnjtranjan** [comment]
catMaybes :: (IsStream t, Monad m, Functor (t m)) => t m (Maybe a) -> t m a
catMaybes = fmap fromJust . filter isJust
is already defined in module Streamly.Internal.Data.Stream.IsStream.
is this requirement for some other module?

**Comment by harendra-kumar** [comment]
We may have introduced it in the meantime. We can close this issue then.
