### ISSUE TITLE
Seedless `unfold` alternative

### ISSUE THREAD

**Issue by shlok** [composewell/streamly#432]
We currently have

    unfold :: (IsStream t, Monad m) => Unfold m a b -> a -> t m b
    
What is your opinion about adding

    unfold' :: (IsStream t, Monad m) => Unfold m Void b -> t m b

This would play nicely with seedless `Unfold`s that someone else has already created using `supply` and provided to you. (Currently, I can use `unfold` with `undefined` as the second parameter, but it seems cleaner if the library could do this under the hood.)

**Comment by harendra-kumar** [comment]
It would be the opposite of:

https://github.com/composewell/streamly/blob/0e2bb73d6cad77fe43d4e675b804d17da18a4407/src/Streamly/Internal/Data/Unfold.hs#L332

it can possibly be called `toStream`? Is it useful? Are you using `unfold` like this?

**Comment by harendra-kumar** [comment]
Or maybe it can be called `unfold0` i.e. an unfold without a seed.

**Comment by shlok** [comment]
My use case: I have code (in a separate library) that creates such an `Unfold` (the library provides the seed internally). Other code (in a different project) wants to turn this `Unfold` into a stream.

Regarding `unfold0` (accompanying `unfold` in `Streamly.Prelude`) vs. `toStream` (accompanying `fromStream` in `Streamly.Internal.Data.Unfold`), I'm not myself sure.

**Comment by shlok** [comment]
@harendra-kumar Looking at [this](https://github.com/composewell/streamly/issues/426) (“…it will make unfolds equivalent to streams.”), what is the eventual plan w.r.t. streams and unfolds? (This PR seems relevant only if both streams and unfolds exist.)

**Comment by adithyaov** [comment]
> Looking at this (“…it will make unfolds equivalent to streams.”), what is the eventual plan w.r.t. streams and unfolds?

Both streams and unfolds will coexist. While streams provide a more convenient API, unfolds are more powerful than streams. In some cases unfolds might be more performant than the corresponding stream combinators. Unfolds are something new and there is much to study about them.

> (This issue (#432) seems relevant only if the plan is for both streams and unfolds existing.)

Yes, this issue is relevant as that is the tentative plan.
