### ISSUE TITLE
filterM is not concurrent, but mapMaybeM is

### ISSUE THREAD

**Issue by eschnett** [composewell/streamly#454]
I found out that `filterM` is not concurrent. I don't know whether it is supposed to be.

Luckily, `mapMaybeM` is, so it is easy to rewrite code. It would be good to update the documentation to describe this – the documentation mentions that `mapMaybeM` is concurrent, but does not speak about concurrency for `filterM`.

**Comment by harendra-kumar** [comment]
If the documentation does not explicitly say that a combinator is concurrent, then it is not.

Can it be made concurrent, yes it can be. The next question is - should it be concurrent? It depends on whether the filtering action is expensive to execute. If it is expensive or blocking then executing multiple of them in parallel may save time. We have not yet seen such a case, so we did not bother to make it parallel.

That said, it should be possible to use mapMaybeM to achieve filtering in parallel.
