### ISSUE TITLE
Enhancements to the Fold type

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#455]
#449 introduces stream parsing using a separate parser type which an extension of folds. We would like to bring some of the power of the Parser type to the existing Fold type adding the ability to terminate to the folds. So the basic fold type would be simple yet powerful enough to express terminating folds like `any`, `all` efficiently but it would not have backtracking capability which will be provided by the more complex `Parser` type which would be just an extension of folds to add backtracking. Backtracking adds significant complexity so it makes sense to have it as a separate type.

This will require the return type of fold step to be a functor like the Parser type:

```
data Step s = Yield s | Stop s
```

And the Fold type would be:

```
data Fold m a b = forall s. Fold (s -> a -> m (Step s)) (m s) (s -> m b)
```

This is a balance between the power and simplicity. Note that this is a consumer side dual of the `Stream/Unfold` types with similar/corresponding constructors. Later we can also add the `Skip` constructor which can help in processing the input in groups i.e. yielding after consuming multiple items rather than yielding on each item.

**Comment by harendra-kumar** [comment]
Let me elaborate a bit more why we should make this change. In general there are three top level domains that we are dealing with, namely (1) producers (unfolds), (2) transformations, (3) consumers (folds). Here we are dealing with the problem of expressing consumers to solve problems.

## A general fold type

Currently we use the `Fold` type for consumers, it is the simplest possible representation of consumers but it lacks in power. Many possible variants of the type can be created to add more power to it. Let's represent a generalized `Fold` with the following type for illustration:

```
data Fold m a b = forall s. Fold (s -> a -> m (Step s)) (m s) (s -> m (Result b))
```

By choosing different `Step` and `Result` functors we can add more power to the fold. Let's list them down in increasing power.

### Non-terminating and Never Failing

Using the Identity functor in the general type we get the current `Fold` type used in streamly, this is the simplest possible fold type.

```
Step s = Identity s
Result s = Identity s
```

This type expresses folds that can never fail and never terminate. They will consume all of the stream unless an explicit termination is used by the fold driver. It allows a useful `zip` applicative by distributing input to all folds and zipping the results, but the zip would also consume all of the stream. It can express full folds like `sum`, `maximum` etc and compose them using zip applicative.

Partial folds like `null`, `head`, `any`, `all` are almost useless in this representation other than in a zipping composition. This fold cannot have an `append` style applicative composition because the first fold itself will run forever and never terminate, for the same reason it cannot be applied repeatedly to a stream without using an explicit termination condition (e.g. `splitBy` combinator). 

### Terminating but Never Failing

We can add termination to the above type to get a bit more powerful type.

```
data Step s = Yield s | Stop s
Result s = Identity s
```

This type expresses a fold that can terminate but never reject an input and never fail. At each step this fold necessarily consumes the input and produces a success result (`Yield s`). `Stop s`  indicates consumption of the input and a terminating success result.

* We can express all the partial folds like `head`, `any` etc. efficiently, the fold driver gets to know when the fold has finished and it can terminate the fold. 
* In addition to the previous type, in this type we have a useful `append` style applicative to compose multiple folds in a chain. We can apply a fold repeatedly to a stream e.g. we can apply a `take` fold repeatedly to consume a stream in chunks. 

However, this fold cannot express failure, so we cannot write an `Alternative` instance to run an alternative fold if a fold fails. This fold cannot reject any input and cannot backtrack in any way. An input given to the fold is considered consumed.

### Failing with backtracking

We can add failure to the previous type and get an even more powerful fold type:

```
data Step s = Yield s | Stop s | Skip s
Result s = Either String (Int, s)
```

This type expresses a fold that may not produce output on each input, it may skip producing output and it can fail to produce any output at all or it can reject some input at the end. The driver keeps all the input until the fold succeeds or fails. When the result is extracted it tells how much input it did not consume along with the result. If the fold fails the driver backtracks fully from the beginning of the input.

This fold is very general and can express parsing with backtracking. However it needs to buffer the input completely even when it may succeed because some of the input at the end may be rejected.

### Failing with incremental backtracking

The previous type is quite general but inefficient. We can make it more efficient by releasing the backtracking buffer incrementally as soon as a result is available instead of always keeping the whole input, the fold cannot fail after an incremental result is available.

```
data Step s = Yield Int s | Stop Int s | Skip Int s
Result s = Either String s
```

This can express all the previous types efficiently, this is in fact an efficient backtracking parser. `Yield n s` generates a result and count of unconsumed input, `Stop n s` is same as yield but indicates termination, `Skip n s` indicates lack of result or backtrack by `n` input items.

## Fold Types in Streamly

Should we use a single most general fold type in streamly or multiple types for different levels of expression?

* The current `Fold` type is the first one described above. It has an issue with partial folds as it necessarily consumes the whole stream even for folds like `head`. The second fold type described above generalizes this to termination but still has the properties from usage perspective.
* The last fold is the most general but it may be inconvenient to use when we know the fold always succeeds, but we still need to handle the error case, also in some cases it may have difficulty in optimizations because of a more complex type. Also, the simpler fold type provides better guarantees against programming errors for those cases.

The middle ground is to use one most general `Fold` type for "always succeeding" folds i.e. the second type above, it solves the partial folds issue in the current type, and one most general fold type for "folds that can fail" i.e. the last type above, we can call it `Parser`.

This is the rationale for this particular issue. Any feedback is welcome.

**Comment by pranaysashank** [comment]
https://github.com/composewell/streamly/issues/543
