### ISSUE TITLE
`fromBytes` problem

### ISSUE THREAD

**Issue by mryndzionek** [composewell/streamly#465]
I have a problem with [fromBytes](https://hackage.haskell.org/package/streamly-0.7.1/docs/Streamly-Internal-FileSystem-Handle.html#v:fromBytes). It seems that in usecase like this:
```hs
fromBytes h $ S.take x $ sourceStream
```
with some lengths (`x`) last chunk of stream is not written to file. Flushing on file handle doesn't help, so I suspect the data is lost somewhere in [chunksOf](https://hackage.haskell.org/package/streamly-0.7.1/docs/src/Streamly.Internal.Prelude.html#chunksOf). Is there a way to force a 'flush' without modifying the internals of Streamly?

**Comment by pranaysashank** [comment]
Are you closing the file handle afterwards? Let me also check the implementation for any bugs.

**Comment by mryndzionek** [comment]
Oh sorry. You are right. The file wasn't being closed properly. Thanks!
