### ISSUE TITLE
Build fails with primitive package 0.6.3.0

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#466]
That is the primitive version provided on stackage lts-12.1, since we support ghc-8.4.3 we should fix this. The problem seem to be in the duplicated code in `Internal.Data.Prim.Array.Types`.

@saurabhnanda brought this to notice on gitter.

**Comment by adithyaov** [comment]
`primitive-0.6.3.0` is deprecated. I think the better option is to maybe update the `primitive` version on stackage ecosystem?

**Comment by pranaysashank** [comment]
I don’t think that’s realistic or possible

**Comment by adithyaov** [comment]
Do you mean `lts-12.1` is locked? Can't the package versions be updated? If so, I think a simple solution is to add `primitive` to `extra-deps`.

**Comment by adithyaov** [comment]
Build fails with primitive package < 0.6.4. I don't think deprication is the problem.

**Comment by pranaysashank** [comment]
Can't close until there's a release.

**Comment by pranaysashank** [comment]
streamly-0.7.2 is now released.
