### ISSUE TITLE
Make sure that the MonadError instance is correct

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#48]
We need to test the MonadError instance using `throwError` and `catchError` the same way we test exceptions in #47. 

We need to make sure that MonadError follows the following laws:

```
throwError e `catchError` f = f e
m `catchError` throwError = m
(m `catchError` f) `catchError` g = m `catchError` (\x -> f x `catchError` g)
```

**Comment by harendra-kumar** [comment]
MonadError instance is not working correctly for parallel compositions. The error state needs to be transferred from the child thread to the parent thread for this to work properly. I have removed the instance for now but this must be fixed soon. Failing tests are already present but disabled in `test/Main.hs`.

**Comment by harendra-kumar** [comment]
`MonadError` instance has been removed, so this is no longer a bug, instead an enhancement.

**Comment by harendra-kumar** [comment]
This is dependent on the definition of concurrency semantics and possibly creation of a typeclass to merge the concurrently modified states of a Monad.

**Comment by harendra-kumar** [comment]
As of now exceptions can be thrown inside stream monads as it provides a `MonadThrow` instance. However, exceptions cannot be caught inside stream monads as there is no `MonadCatch` instance available yet. Though you can always catch exceptions when you are outside the stream monad i.e. once you have run the stream and lowered it to the IO monad.

I still need to find some time to work on providing better ways to handle exceptions especially in concurrent compositions, but in the meanwhile if you can provide your specific case we can try to find a solution or workaround.

**Comment by nhenin** [comment]
So, I'm using haskell servant for a webServer and I want to throw an ServantErr when an exception occurs in my stream : 

```
streamCommand :: WorkspaceId -> Handler (P.Producer (Persisted GsdCommand) IO ())
    streamCommand workspaceId =
        catchError
          (stream)
          (\exception @ SomeException {} -> do
          liftIO $ logInfo logger "catching errors from streamly"
          throwError err500)
       where
         stream :: Handler (P.Producer (Persisted GsdCommand) IO ())
         stream = do
            return $ toPipes $ GsdMonitoring.streamCommand
                                  eventStoreSettings
                                  workspaceId

streamCommand ::  Streamable stream monad Command => EventStoreSettings -> WorkspaceId -> stream monad (Persisted GsdCommand)

class (FromJSON item,
       Monad monad,
       IsStream stream,
       MonadIO (stream monad),
       MonadAsync monad,
       Semigroup (stream monad (Persisted item))) => Streamable stream monad item

```

That how I would like to do it if the MonadError Instance was available.

**Comment by harendra-kumar** [comment]
You can always use `ExceptT` with streamly, but since `MonadError` instance is not available you will have to use `throwE` and `catchE` along with `lift` instead of using throwError/catchError. Though if you are throwing from concurrent code, it may not work correctly, serial streams should work fine.

**Comment by harendra-kumar** [comment]
We do not have a MonadError instance and it is unlikely that we will add it in near future. The stream types in the new release are not even a Monad by default.
