### ISSUE TITLE
Associativity of <> operator

### ISSUE THREAD

**Issue by tymefighter** [composewell/streamly#492]
The semigroup operator is assumed to be associative, but the operators for streams like WSerialT are not associative (and are in fact right associative). This has not been mentioned in the doc, so I think the doc should be updated for this.

**Comment by harendra-kumar** [comment]
None of the streams except SerialT have an associative <> in the positional sense of equivalence. If we change our notion of equivalence then we can say they are associative. AheadT is associative wrt stream output but not wrt side effects. If we consider a multiset equivalence then all of them are associative.  

When <> says it is an associative operation it does not define using which equivalence method.  For example, AsyncT streams are considered unordered, therefore they should be compared ignoring the order. 

We can mention this in the docs.

**Comment by harendra-kumar** [comment]
closing this in favor of #513.
