### ISSUE TITLE
Applicative instance of Fold and the new Tee type

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#499]
See also #455 .

Since we are now including terminating/splitting functionality under the 'Fold' type we need to reconsider the existing applicative instance. The current applicative instance is consistent with the `foldl` library. However, with terminating folds a splitting applicative like the `Parser` type is possible for `Fold`. 

To keep Folds consistent with Parsers we can change the applicative instance of folds to a splitting applicative. The current applicative would become a `teeWith` function like in Parsers. This would be a breaking change. To mitigate the impact of the change to existing users we can have a new `Tee` type whose applicative would behave just like the current Fold applicative. This would be similar to the way we have `ZipSerial` type in streams.

**Comment by harendra-kumar** [comment]
1) We can deprecate the applicative instance of Fold in the major release and in a future release we switch it to parser like applicative.
2) We will need continuation style folds along with direct syle folds (like we have in parsers) to make the applicative instance scale well for infinite applications of folds.

**Comment by pranaysashank** [comment]
https://github.com/composewell/streamly/pull/488

**Comment by harendra-kumar** [comment]
Since we cannot deprecate the instance, we should remove the instance and add instructions to changelog about what to use in its place. Otherwise if we change this in the next release it may introduce silent bugs because of the change of behavior without users knowing about it.

**Comment by adithyaov** [comment]
See #965
