### ISSUE TITLE
missing import, extensions in examples of readme.md

### ISSUE THREAD

**Issue by pcarbonn** [composewell/streamly#5]
I get an error when running the `loops` examples in the readme file.  

    Parse error: $
    Perhaps you intended to use TemplateHaskell

I have not yet found the time to look at TemplateHaskell...  Any hint welcome.

For the "sum of the square roots" example, I get "ambiguous type variable 'm0' arising from a do statement", in the line with the `forEachWith`.  Am I missing an extension ?

I could get the other examples to work.  They look great !  Many thanks for this package!

**Comment by harendra-kumar** [comment]
There was an extra `$` before the do block in the loops example. The sqrt example used print on a monadic value. I fixed these and also added explicit imports. The GHC errors can be really cryptic sometimes.

Thanks for reporting and sorry for not testing the examples well before publishing. Let me know if you face any other problem.
