### ISSUE TITLE
remove tapRate in favor of pollCounts

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#507]
We have these two combinators to do the same thing. The functionality of `tapRate` is subsumed by `pollCounts` we can remove that combinator. Presence of both of these would be confusing. We need to do performance comparison before removing.

**Comment by rnjtranjan** [comment]
tapRate 1 second:                                                  OK (0.22s)
        264  μs ±  23 μs
      pollCounts 1 second:                                               OK (0.37s)
        261  μs ±  23 μs
