### ISSUE TITLE
Break down test/Prop.hs and test/Main.hs into smaller modules

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#510]
#146 is about organizing tests by source modules. This issue is from build perspective. First of all we need to enable optimization options, same as for benchmarks or at least `-O2` for all tests. This is also required for `fusion-plugin` to work on tests. But `-O2` currently takes inordinate amount of time and memory (~6GB) to compile `Prop.hs` and `Main.hs`. We need to break down these modules into smaller modules so that we can compile them in reasonable amount of time and memory. At the same time the tests can go into their own respective modules corresponding to source modules where applicable.

See also #433 . The test modules can also be broken down on the same lines.

**Comment by pranaysashank** [comment]
- [x] Break down test/Prop.hs (#611)
- [ ] Break down test/Main.hs
