### ISSUE TITLE
Are 32-bit ci builds working as intended?

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#514]
@hasufell 

I am not sure if this CI entry is working correctly:

```
  - env: BUILD=cabal-v2 GHCVER=8.4.4 GHC_OPTIONS="" CABAL_BUILD_OPTIONS="--flag debug"
    addons: {apt: {packages: [cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
    os: linux
    arch: x86
```

* Travis config validator shows an error if `arch:x86` is passed.
* But I see that the travis build shows x86 architecture on the build entry
* However, I did not find any evidence in the build logs that 32-bit is being used, it shows amd64 as arch in `build system information`.
* The info printed by packcheck:

```
OS: Linux
Architecture:          x86_64
```

Also, don't we have to use 32-bit ghc for 32-bit builds? The above entry is using ghc from `hvr-ghc` which does not seem to have any 32-bit versions of ghc.

**Comment by harendra-kumar** [comment]
See this build for example: https://travis-ci.com/github/composewell/streamly/jobs/323354712

**Comment by hasufell** [comment]
Yeah, I'm not sure how to do this with travis, it seems they're not supporting it:

* https://github.com/travis-ci/travis-ci/issues/986
* https://github.com/travis-ci/travis-ci/issues/5770

I think it should be doable in a 32bit docker container: https://hub.docker.com/r/i386/ubuntu/
You can use ghcup to install a 32bit ghc and cabal: https://downloads.haskell.org/~ghcup/

**Comment by harendra-kumar** [comment]
Would you like to try out the docker option?
