### ISSUE TITLE
Track internal API usage

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#518]
We use Internal modules for experimental and unstable APIs which may or may not eventually make it to supported/exposed APIs, or the signatures/names etc may change before they are released.

We have release plans to open many such APIs. This is issue to track external usage of Internal APIs so that we can take that into consideration as a feedback and also cause least disruption to the users of Internal APIs.

Here are some usages that I noticed, please feel free to add to this list:

* https://packdeps.haskellers.com/reverse/streamly
* https://github.com/mryndzionek/composable-sdr
* https://github.com/BeFunctional/streamly-frames

**Comment by harendra-kumar** [comment]
Let's review the APIs in use by the libraries that depend on streamly and try to expose the internal APIs being used by these so that these libraries can be better supported.

**Comment by harendra-kumar** [comment]
https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/master/ghcup.cabal

**Comment by pranaysashank** [comment]
### Streamly.Internal.Data.Fold
- Fold
- runStep
### Streamly.Internal.FileSystem.File
- toBytes
- toChunksWithBufferOf
- writeChunks
### Streamly.Internal.Memory.Array.Types
- Array (..)
- newArray
- shrinkToFit
- spliceTwo
- splitAt
### Streamly.Internal.Memory.ArrayStream
- concat
### Streamly.Internal.Data.Stream.StreamD.Type
- fromStreamD
- Step(..)
- Stream(..)
### Streamly.Internal.Data.Unfold.Types
- Unfold (..)
### Streamly.Internal.Data.Unfold
- finallyIO
