### ISSUE TITLE
Replace Streamly.Memory.Array with Pinned PrimArray

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#538]
Prim Arrays are actually a bit faster compared to `Streamly.Memory.Array`. In some cases it can make a significant difference. In a `classify` example which uses short strings, PrimArray reduced the timing from 2.6 to 1.7 seconds.

it may be a good idea to get rid of Data.Memory.Array and just use Pinned PrimArray instead everywhere. We will have one less data structure to get confused with.

**Comment by harendra-kumar** [comment]
Note: have to compare the speedup after removing the extra pointer from Streamly.Memory.Array.

**Comment by adithyaov** [comment]
Isn't `Streamly.Memory.Array` basically pinned `PrimArray`?

**Comment by harendra-kumar** [comment]
`Streamly.Memory.Array` uses a `ForeignPtr` and `Storable` typeclass whereas `PrimArray` uses `ByteArray` directly and uses the `Prim` typeclass.

**Comment by adithyaov** [comment]
Closed in favor of #1677
