### ISSUE TITLE
Performance regression tests in CI

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#582]
GC allocations provide a pretty good and stable measure of performance, we can use that to reliably report performance regressions automatically in CI. bench-show already detects regression percentage, we can set a threshold for auto reporting the top regressions and fail the CI. We need to take care of the following:

1) run just one iteration of each benchmark using gauge so that benchmarks run really fast
2) building `bench-show` can take a lot of time, we should use a pre-built binary or cache it. Even if we cache it, building it for the first could still be pretty heavy.

**Comment by adithyaov** [comment]
As discussed on discord,

    Look at how GHC have automated benchmark regression tests.
    One interesting thing they have is "instruction count", that should be a stable measure like allocations, we can reliably test that in automation. CPU time/cycles are very unreliable in comparison. We should introduce an instruction count measure.
    Instead of using gauge we can have a simple module in streamly itself to measure such metrics. We anyway must have that as a diagnostic tool in streamly.

**Comment by adithyaov** [comment]
See #745
