### ISSUE TITLE
Improve bench-show and eliminate Chart.hs

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#598]
`Chart.hs` is quite general and not benchmark specific anymore. We can transfer its behavior to the executable provided by `bench-show` itself. We should be able to use `bench-show` directly.

**Comment by harendra-kumar** [comment]
Can you describe exactly what is required from `bench-show` and create an issue for `bench-show`?

**Comment by adithyaov** [comment]
I think `bench-report` is specific and uses `bench-show` as a library. I had the benchmarking CI in mind while opening this.
