### ISSUE TITLE
Unfold routines and tests

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#609]
We have not yet exposed any of the Unfold APIs, we should do that in the next release. Before we do that we need to do the following:

* Write tests for all the existing unfold APIs
* Complete the repertoire of unfold APIs. Most stream APIs can have corresponding unfold APIs. Investigate which stream APIs are applicable and implement those.

**Comment by pranaysashank** [comment]
@adithyaov Can you update the status of this issue.

**Comment by adithyaov** [comment]
Closing this. Looks like all the unfolds have benchmarks and tests.
