### ISSUE TITLE
Rename Streamly.Internal.Mutable.Prim.Var

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#619]
Move `Streamly/Internal/Mutable/Prim/Var.hs` => Streamly.Internal.Data.IORef.Prim

We can make the functions in this module as IO functions and name them after IORef functions. This would make it easier to understand and use for those who already know IORef, so this just becomes an IORef specialized to Prim.

**Comment by pranaysashank** [comment]
Thinking the module name should be `Streamly.Internal.Data.Ref.Prim` instead

**Comment by pranaysashank** [comment]
We have decided that we'll go with `Streamly.Internal.Data.IORef.Prim`
