### ISSUE TITLE
MonadBaseControl instances for stream types

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#63]
The underlying monad of a parallel stream needs a MonadBaseControl instance for forking a thread. This is find when we have IO or any other monad as the underlying monad, but since none of the stream types are MonadBaseControl instances they cannot be used as the underlying monad for a stream Monad. 

This issue is for exploring how to make the streams instances of MonadBaseControl or maybe MonadUnliftIO. We should revisit this only after we are done with #29.

**Comment by harendra-kumar** [comment]
We can perhaps thread the state through SVar and then restore it once the run action is done. So this may depend on #73 .

**Comment by harendra-kumar** [comment]
Its not possible to create a `MonadBaseControl` instance for a continuation type as the state of the monad is embedded in functions and cannot be captured and restored. However, we do not need a MonadBaseControl instance really, this is too powerful for our job. We can do with something much simpler like a `MonadFork` which just allows running an action inside an inner monad using the current state of the outer monad and discard the result. I guess almost all monads can trivially be made instances of this.

**Comment by chshersh** [comment]
I would like to see `MonadUnliftIO` used instead of `MonadBaseControl`. The motivation for this in simple words: `MonadBaseControl` allows to use more monads, but they are not safe to use and hard to reason about in the context of concurrent computations.

**Comment by harendra-kumar** [comment]
@chshersh see also #105 on the same topic. The problem is UnliftIO precludes all stateful monads and the only way to maintain state is to use an IORef. I would like `StateT` to work with streamly and have concurrent semantics for powerful concurrent programming. As I mentioned earlier in this issue, we are exploring a less powerful typelcass to fork the state and join it back when the concurrent computations merge. This would be a middle ground, not as powerful as MonadBaseControl but not as powerless as UnliftIO, and should be easy to reason about. But this work may take some time as we are inundated with a lot of other work.

**Comment by chshersh** [comment]
@harendra-kumar Ah, I wasn't aware that you're working on a middle ground solution between `MonadUnliftIO` and `MonadTransControl`. Looking forward to seeing this abstraction; should be interesting!

**Comment by harendra-kumar** [comment]
Streams are not monads by default in the upcoming release.
