### ISSUE TITLE
implement takeP parser

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#630]
This is a simple modification of the take Parser so that it can take a Parser instead of a Fold as argument. This would be useful in e.g. `takeP (takeWhile (/= 0)) 10` i.e. terminate at a null or max 10 elements. I needed this in the event parsing for inotify, I have used a hack for now (using `sliceSepByMax`).

**Comment by harendra-kumar** [comment]
I think terminating folds PR will take care it as the fold will become terminating we may not need a parser argument.

**Comment by harendra-kumar** [comment]
With terminating folds, the current `take` parser functionality will move to the Fold module and we can use the name `take` for `takeP` in the Parser module.

**Comment by adithyaov** [comment]
Closed by https://github.com/composewell/streamly/pull/1171
