### ISSUE TITLE
Better documentation page

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#635]
Create a custom doc page from haddock to address the following:

1) List the modules on a fixed module index pane on the left side and the contents of the module displayed on the right.
2) In the index pane we want to display the modules in a certain selected order and omit some of the modules

**Comment by pranaysashank** [comment]
Given that 2nd one is the one that we can tackle relatively easily, what is the order that we want to display them.

**Comment by harendra-kumar** [comment]
You can choose an order, we can discuss/change that before commit.

**Comment by harendra-kumar** [comment]
Other things to do:

* Show modules for linux/windows/macOS at the same time
* hide deprecated modules

* We can possibly use custom haddock pragmas to hide selected modules.
* We can decide the ordering based on the ordering in the cabal file or using an ordering pragma.

**Comment by harendra-kumar** [comment]
This has been addressed. We have the documentation on https://streamly.composewell.com now.
