### ISSUE TITLE
Benchmarks don't build with GHC 8.10

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#648]
Many libraries we depends on haven't been updated to use base 4.14. This issue is to track the upstream changes. Meanwhile we can use this project file to build with 8.10.

```
packages: ./ ./benchmark/streamly-benchmarks.cabal
allow-newer: diagrams-svg:base monoid-extras:base diagrams-postscript:base statestack:base diagrams-lib:base dual-tree:base active:base diagrams-core:base

source-repository-package
    type: git
    location: git@github.com:sjakobi/svg-builder.git
    tag: ff3a4b0fdfcdf8cfa0d08564733024b63121bd65

```

**Comment by harendra-kumar** [comment]
@pranaysashank  is it still the case or can we close this?

**Comment by pranaysashank** [comment]
It is still the case, I still don't see any updates on hackage.

**Comment by harendra-kumar** [comment]
This is only for bench-show and not the core benchmarks. We can build bench-show using older compilers.
