### ISSUE TITLE
Mutable array support

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#660]
Create a `Streamly.Data.Array.Mut` module for mutable arrays. This module will contain mutable APIs like `writeIndex`, and other range based writing APIs.

**Comment by harendra-kumar** [comment]
* Create Data.Array.Foreign.Mut module
* The import list in Streamly.Internal.Data.Array.Foreign has many mutable array module functions commented out, there may also be corresponding commented out code, move all these to new module
    * writeIndex etc.
    * partitionBy etc.
* Mutable array APIs: Many of the APIs from Streamly.Internal.Data.Array.Foreign.Mut.Type can be directly exported via Streamly.Internal.Data.Array.Foreign.Mut module.
* The mutable array APIs would have return type monadic instead of pure.
* Perhaps defaultChunkSize et al can be moved to some common IO module like Streamly.Internal.System.IO. It is used across many modules and it is not specific to arrays as such.

**Comment by adithyaov** [comment]
This is closed by #1155 and #1162
