### ISSUE TITLE
Add a "retry" combinator

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#664]
Under Streamly.Prelude exception handling combinators:

```
retry :: (MonadCatch m, Exception e)
    => Map SomeException Int  -- map from exception to retry count
    -> (e -> Stream m a) -- default handler for those exceptions that are not in the map
    -> Stream m a
    -> Stream m a
```

This will make use of the new `ghandle` combinator which passes the remaining stream to the exception handler, so that the exception handler can choose to resume executing the stream. We can maintain the retry count in the monad, when the count reaches zero we can return a nil stream or raise an exception.

**Comment by adithyaov** [comment]
Closed by #1176
