### ISSUE TITLE
Rename "lfilter", "ltake" etc. for folds to make these consistent with naming in parsers

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#665]
Folds and Parsers should be assumed to be operating on the input by default. So we can drop the `l` prefix and just use `filter`, `take` etc, just like we do in parsers.

To be consistent I would like `lmap` to also become just `map`. So the `map` for Folds and Parsers would be map on input whereas `fmap` would be the usual  map on output. This is a case where `map` and `fmap` would not be the same. This goes against the established intuition but I think `map` need not necessarily be the same as `fmap`.

**Comment by harendra-kumar** [comment]
Since these are not exposed yet, let's fix them in 0.8.0 itself.

**Comment by harendra-kumar** [comment]
`lsessionsOf` is called `intervalsOf` in streams, so make it consistent.

**Comment by harendra-kumar** [comment]
The `mapM` and `sequence` operations in the `Fold` module should be deprecated to later replace these later by the contravariant definitions.

For folds the natural/default transformations are contravariant. For covariant map we have `fmap`, for covariant `mapM` equivalent we can use `rmapM`.

**Comment by adithyaov** [comment]
See #868
