### ISSUE TITLE
Need tests for folds

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#675]
The following APIs which are exposed to the users do not have any tests:

* drain
* drainBy
* mean
* variance
* stdDev
* mconcat
* foldMap
* foldMapM
* lookup
* sequence
* mapM
* tee
* distribute
* partition
* unzip

1) We need tests for these even if it is a trivial test. Without tests, we won't even know if an operation got accidentally removed during refactor. The recent Fold changes are all pervasive and I am concerned that it might break some of these routines which do not have any tests.

2) The test file for folds is not properly formatted, we need to format it.

3) Several routines in `Streamly.Internal.Data.Fold` also require tests.

**Comment by rnjtranjan** [comment]
Following test cases are missing:
sequence
mapM

**Comment by harendra-kumar** [comment]
`sequence` is now deprecated. `mapM` is renamed to `rmapM` so just a testcase for `rmapM` should be enough.

**Comment by rnjtranjan** [comment]
Both are DEPRECATED and replaced by rmapM
