### ISSUE TITLE
Unable to run individual benchmarks

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#676]
```
$ cabal bench Prelude.Async
cabal: The bench command is for running benchmarks, but the target
'Prelude.Async' refers to the test suite Prelude.Async from the package
streamly-0.7.2.
```

If I run this command inside the `benchmark` directory then it rebuilds streamly. Also, we need a cabal.project.local there to pick up the local streamly.

1) rename the tests using a Test prefix e.g. `Test.Prelude.Async`
2) add a `cabal.project.local` in the `benchmark` directory to pick the local streamly lib, just in case we want to use it

**Comment by harendra-kumar** [comment]
We can run the benchmarks by invoking the executables directly, but I think we should be able to use the `cabal bench` command as well.

**Comment by pranaysashank** [comment]
Does it work with a different name? Did the command work before?

**Comment by harendra-kumar** [comment]
Its only an issue for the cases where benchmark names conflict with test names.

**Comment by adithyaov** [comment]
Prefixing it the word `bench:` solves the issue.
