### ISSUE TITLE
Rename `take` to `takeLE`?

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#680]
I made a mistake in using the `take` parser when parsing a message header. I used it where I actually meant to use `takeEQ`. Should we rename `take` to an explicit `takeLE` to avoid mistakes?

We should then rename the Fold and Stream versions of take as well to keep it consistent? `take` has been named to keep it consistent with the wide use of this operation in `base` and elsewhere. But I think it would be better to have clearer names to avoid mistakes especially when operations like `takeEQ` and `takeGE`exist.

**Comment by adithyaov** [comment]
See #868
