### ISSUE TITLE
Add byte stream to UTF-16 encode/decode routines

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#693]
It could be useful for interfacing with windows APIs and also for conversion to/from  other utf-16 encoded data e.g.`text`.

See the [utf8 impl](https://github.com/composewell/streamly/blob/ad05792d0b361c4629fc3009f69e21988eeaae88/src/Streamly/Internal/Unicode/Stream.hs#L253) for reference.

**Comment by adithyaov** [comment]
See https://github.com/composewell/streamly/pull/2662

**Comment by adithyaov** [comment]
This can be closed.
