### ISSUE TITLE
Request for comments: API naming and signatures

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#7]
# Compatibility with base/Data.List

Streamly streams are very similar to the standard Haskell lists in nature and in signatures. The only difference is that streamly streams are monadic. If one knows a list function he/she should know that it works exactly the same way in streamly. In other words, streamly streams are just better and generalized lists that come in the form of monadic streams with safe concurrent composition. 

For consistency, we strive to keep all streamly functions on the lines of `base:Data.List` functions as long as it makes sense and is possible. 

## Differences with Lists

Following are some differences that we have or may deliberately concede compared to `base/Data.List`. 

The main difference is due to the fact that streamly streams are monadic while lists are pure.

* `streamly` streams are not instances of `Foldable` and `Traversable` though they provide equivalent functionality without the type classes.
* Fold functions have slightly different but similar signatures
* Monadic traversal functions like `mapM` and `sequence` have slightly different but similar signatures
* We also have monadic versions of APIs (APIs that take a monadic function instead of a pure one) where ever it makes sense. These APIs are generally suffixed with an `M`.

The other key difference is due to partial functions:

* We may not have partial functions like `tail`, `head` instead we may have safe versions of those having the same name but a different signature returning a `Maybe`.

# Compatibility with foldl/Control.Foldl

We would also like the streamly fold like functions that work with the `foldl` library. For that we need fold functions with an extraction argument and we should name them differently from the standard ones. We can perhaps reuse the name `fold` (as streamly does not have a `Foldable` instance) for such a composable fold function. Similarly the name `scan` can be used for a composable scan.

# Changes required

Let's fix if anything is currently deviating from these conventions. I can see the following:

* `foldl` to be renamed to `fold` and we can have list compatible `foldl` written in terms of `fold`. We do not have a `Foldable` instance so this name will conflict with that.
*  similarly `foldlM` to be renamed to `foldM`

**Comment by harendra-kumar** [comment]
@Abhiroop let's name the composable `Control.Foldl` compatible `scanl` function as `scan` and the list compatible scanl function as `scanl`. `scanl` can just be `scan` with `id` as the extraction function.

**Comment by Abhiroop** [comment]
@harendra-kumar Renaming https://github.com/composewell/streamly/pull/6/commits/c4f33d7b63b86a9c254717bc399ff8bc5e76f16b

**Comment by harendra-kumar** [comment]
See also #39

**Comment by eddiew** [comment]
I'm not sure if this is the right place to ask, but why not make streamly streams instances of `Foldable` or `Traversable`? If equivalent functionality is provided, it seems like providing these instances would solve the compatibility problem.

**Comment by harendra-kumar** [comment]
PR #120 adds a document explaining the similarity and differences between Haskell lists and streams.
