### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#719]
Some concurrent tests keep failing on Appveyor, most of them are timing tests.

One of them is
```
streamly           > Parallel (<>) time order check
streamly           >   Parallel ordering left associated
streamly           >   Parallel ordering right associated FAILED
```

**Comment by pranaysashank** [comment]
takeByTime, dropByTime tests keep failing intermittently. These are not concurrent as well, need to investigate why they are happening.

**Comment by harendra-kumar** [comment]
These also deal with timing. We can move these too in dev build.
