### ISSUE TITLE
Write automated tests for fs event handling

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#724]
We have  manual test in `test/Streamly/Test/FileSystem/Event.hs`. This can be converted to an automated test, by running the event watch in one thread and generate events by doing some filesystem modifications in another thread. We can create a temporary sandbox directory for generating events and perform dir tree modifications under it.

**Comment by harendra-kumar** [comment]
@rnjtranjan isn't this already fixed? Can we close this?

**Comment by rnjtranjan** [comment]
Fixed in https://github.com/composewell/streamly/issues/696
