### ISSUE TITLE
Create a common fs events handling API for Linux/Windows/macOS

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#726]
We now have fs event handling for all these platforms. We need find the common subset of APIs that can be supported on all of them and expose that through Streamly.FileSystem.Event module.

**Comment by harendra-kumar** [comment]
To start with we can:

* create a `FileSystem.Event` module
* import the os specific events module in this using CPP macros (as we do in the tests/example module)
* make sure the signatures and names of the corresponding APIs match for all os specific modules
* export the common APIs
* write a test module to use all these APIs, if we can compile that module on all platforms it means the signatures are the same on all platforms.

**Comment by rnjtranjan** [comment]
currently I feel these APIs are common:
module Streamly.FileSystem.Event
    ( Event.Event (..)
    , showEvent
    , toUtf8
    , watchPaths
    , watchPathsWithMask
    , watchTrees
    , watchTreesWithMask
    )
where

**Comment by rnjtranjan** [comment]
watchPathsWithMask 
    :: NonEmpty (Array Word8) 
    -> NonEmpty Word32 
    -> SerialT IO Event.Event
watchPathsWithMask paths masks = 
    Stream.filter matcher $ Event.watchPaths paths
    
    where

    matcher ev =
        Set.member (Event.eventFlags ev) $ Set.fromList $ NonEmpty.toList masks        
         

watchTrees :: NonEmpty (Array Word8) -> SerialT IO Event.Event
watchTrees = Event.watchTrees

watchTreesWithMask 
    :: NonEmpty (Array Word8) 
    -> NonEmpty Word32 
    -> SerialT IO Event.Event
watchTreesWithMask paths masks = 
    Stream.filter matcher $ Event.watchTrees paths
    
    where

    matcher ev =
        Set.member (Event.eventFlags ev) $ Set.fromList $ NonEmpty.toList masks
