### ISSUE TITLE
Please add `fmapMaybe`

### ISSUE THREAD

**Issue by Fresheyeball** [composewell/streamly#74]
Since streams can be `filter`ed they should have an instance of `Control.Compactable` or at the very least `fmapMaybe :: (IsStream t, Monad m) => (a -> Maybe b) -> t m a -> t m b`
This would eliminate the following anti-pattern appearing in code:
```haskell
foo = fmap fromJust . S.filter isJust
```

**Comment by harendra-kumar** [comment]
Thanks for the suggestion @Fresheyeball . 

I am trying to keep the API as close to lists and the standard prelude as possible. So I am in favor of a `mapMaybe` and the monadic version `mapMaybeM`:

```
mapMaybe :: (IsStream t, Monad m) => (a -> Maybe b) -> t m a -> t m b
mapMaybeM :: (IsStream t, Monad m) => (a -> m (Maybe b)) -> t m a -> t m b
```

Though, in general the monadic version covers the pure case too. I am not sure if we should include the pure version as well.

**Comment by subbyte** [comment]
Hi @harendra-kumar , I am actually using `fmap fromJust . S.filter isJust` in my code. Could you give a little bit more information where can I find the `mapMaybe` function? I will be happy to use it.

**Comment by harendra-kumar** [comment]
@subbyte `mapMaybe` is not yet implemented. It is what I proposed to add above. I will add it in the next release, in case you feel like implementing it please go ahead and send a PR.

**Comment by harendra-kumar** [comment]
This is done, thanks @subbyte !
