### ISSUE TITLE
A.fromList crashes on empty list of type [()]

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#755]
```
> import qualified Streamly.Data.Array.Storable.Foreign as A 

*Streamly.Prelude A IS FL S> A.fromList ([] :: [()])
*** Exception: divide by zero
```

**Comment by rnjtranjan** [comment]
After fixing Exception: divide by zero, due to the size of () is 0 the length of Array always says 0 irrespective of no of () elements.

**Comment by adithyaov** [comment]
Is this fixed? This looks like a huge problem. `fromList` is a very common function.

**Comment by harendra-kumar** [comment]
The problem is that the unit element's Storable instance returns size 0 which is unusual for a Storable. We can possibly fix this by using `min 1 (sizeOf a)` wherever we use `sizeOf`, an unfortunate complexity to accomodate this weird Storable instance.

**Comment by harendra-kumar** [comment]
Need to add a test case for this.

**Comment by harendra-kumar** [comment]
@rnjtranjan we needed a basic test  for this, that's why the issue was open.
