### ISSUE TITLE
Document folds with termination annotation

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#772]
Some folds never terminate, others terminate on some condition. It will be nice to have an annotation in haddock on each fold whether it terminates or not, and if it terminates then when. For example:

```
-- /Never terminates/
```

```
-- /Terminates on encountering 0 input/
```

**Comment by harendra-kumar** [comment]
We may also want to indicate if a fold can return a `leftover` input, it basically means that the fold uses `Partial1` or `Done1`.

**Comment by adithyaov** [comment]
Termination annotation:

1. Basic Folds
- sum: /Never Terminates/
- fromPure: /Terminates immediately/
2. Composed folds
- take n: ?? A nice way to write this in 1 line? /Terminates after taking n elements/
- split_: ?? A nice way to write this in 1 line?

Instead of adding an annotation, we can add documentation regarding the termination in the haddocks.

For example:

```haskell
-- This is the dual of stream "fromPure".
--
-- | A fold that always yields a pure value without consuming any input.
--
-- /Terminates immediately/
--
-- vs
--
-- __Termination:__ Terminates immediately
--
-- /Pre-release/
--
{-# INLINE fromPure #-}
fromPure :: Applicative m => b -> Fold m a b
fromPure b = Fold undefined (pure $ Done b) pure
```


```haskell
-- | Collect zero or more applications of a fold.  @many split collect@ applies
-- the @split@ fold repeatedly on the input stream and accumulates zero or more
-- fold results using @collect@.
--
-- >>> two = Fold.take 2 Fold.toList
-- >>> twos = Fold.many two Fold.toList
-- >>> Stream.fold twos $ Stream.fromList [1..10]
-- [[1,2],[3,4],[5,6],[7,8],[9,10]]
--
-- Stops when @collect@ stops.
--
-- See also: 'Streamly.Prelude.concatMap', 'Streamly.Prelude.foldMany'
--
-- /Terminates when the collecting fold terminates/
--
-- vs
--
-- __Termination:__
-- @many split collect@ terminates when @collect@ terminates
--
--
-- @since 0.8.0
--
{-# INLINE many #-}
many :: Monad m => Fold m a b -> Fold m b c -> Fold m a c
many (Fold sstep sinitial sextract) (Fold cstep cinitial cextract) =
    Fold step initial extract
```


Additional titled documentation is more elaborate and is more general.

**Comment by adithyaov** [comment]
Maintaining a termination condition for all the combinators is going to be a huge maintenance burden which isn't probably worth it. The termination condition can be specified dependingly, according to the combinator.
