### ISSUE TITLE
Streamly Readme does not match hackage

### ISSUE THREAD

**Issue by xave** [composewell/streamly#773]
Hello. The Readme on the GitHub Readme is slightly out of sync. For instance, it uses `S.aheadly` instead of `aheadly` in the examples. The hackage page shows everything correctly.

**Comment by pranaysashank** [comment]
The README on master branch is consistent with the code on master i.e. the development version. There are tags for each release in the repo, the README that corresponds to the latest release on hackage is on https://github.com/composewell/streamly/tree/v0.7.2r1

**Comment by xave** [comment]
Thank you. This makes sense. I’ll be exploring with the latest release documentation.
