### ISSUE TITLE
Consider using the ghc cpp macro os_HOST_OS=1 in place of custom CPP macros.

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#778]
Instead of using the the custom cpp options, CABAL_OS_DARWIN, CABAL_OS_LINUX, CABAL_OS_WINDOWS, we can the use macros that are available in ghc.

https://downloads.haskell.org/ghc/latest/docs/html/users_guide/phases.html?highlight=cpp#standard-cpp-macros

**Comment by harendra-kumar** [comment]
ghc macros won't work in the C code though.

**Comment by harendra-kumar** [comment]
Let'e keep the existing macros as we use those in the C code as well. @pranaysashank please reopen if you have any other ideas.
