### ISSUE TITLE
serially and asyncly not in scope

### ISSUE THREAD

**Issue by hughjfchen** [composewell/streamly#782]
With the following import:
`import qualified Streamly.Prelude as S`
I got the following error:
`S.serially` not in scope, Module `Streamly.Prelude` does not export `serially`
The version of the `streamly` package is 0.7.2

**Comment by harendra-kumar** [comment]
In 0.7.2 it is in the `Streamly` module, you can add `import qualified Streamly as S`.

**Comment by hughjfchen** [comment]
Thanks for your reply. Looks like a lot of API has been changed since 0.7.2 and many examples don't compile any more.

**Comment by pranaysashank** [comment]
The README (& repo) w.r.t 0.7.2 release on hackage is at https://github.com/composewell/streamly/tree/v0.7.2r1 . That should have examples that compile with 0.7.2. `master` branch is the development version

**Comment by hughjfchen** [comment]
Well, that makes sense. I've been exploring `streamly` with `https://github.com/composewell/streamly-examples` repository. Some examples within that repos may need to be updated, e.g. the `CmdServer.hs`.

**Comment by harendra-kumar** [comment]
What's wrong with `CmdServer.hs`? Does it not compile?

**Comment by hughjfchen** [comment]
It should compile if you clone the whole `streamly-examples` repos because it pins to a specific `streamly` version. But if you copy some examples and try them with `streamly 0.7.2`, like what I did, they won't compile.

**Comment by harendra-kumar** [comment]
We should probably tag the `streamly-examples` repo with streamly release versions and add a note in README about it.

**Comment by hughjfchen** [comment]
Yes, that should works.

**Comment by harendra-kumar** [comment]
I have opened https://github.com/composewell/streamly-examples/issues/7 . closing this one.
