### ISSUE TITLE
Lots of internal APIs used in examples

### ISSUE THREAD

**Issue by hughjfchen** [composewell/streamly#785]
Going through the examples, I'd found a lot of APIs from the `internal` modules used within these examples. That makes me wonder is it possible to build an application based on the public APIs of the library if so many `internal` APIs had to be used even in examples. I've been trying to clean up these examples based on public APIs but made little progress due to lack of knowledge of the library.

**Comment by harendra-kumar** [comment]
We introduce APIs as Internal when we are developing the APIs. The library is evolving and we try to give some soak time to the APIs before we expose them as officially published and long term supported APIs. This means the APIs may remain internal for a releases or two before it stabilizes, users can use these internal APIs and provide feedback.

If you think certain APIs should be exposed, you can mention those in https://github.com/composewell/streamly/issues/518 . We will try taking a look at streamly-examples and consider those for exposing in the coming release.

**Comment by harendra-kumar** [comment]
Raised https://github.com/composewell/streamly-examples/issues/8 . Closing this one.
