### ISSUE TITLE
Support for running parts of a stream in a different monad

### ISSUE THREAD

**Issue by rdnetto** [composewell/streamly#79]
Conduit addresses this problem with [dedicated functions](http://hackage.haskell.org/package/conduit-1.0.11/docs/Data-Conduit-Lift.html) for some common monads. Currently the only alternative is to use [hoist](http://hackage.haskell.org/package/mmorph-1.1.2/docs/Control-Monad-Morph.html#v:hoist), but as described [here](https://github.com/snoyberg/conduit/wiki/Dealing-with-monad-transformers) this is broken for stateful monads (AIUI, it's equivalent to `transPipe`).

My use case is that I wanted to add a state monad to process part of the stream without leaking its implementation (the type of the state) to the rest of the transformer stack.

**Comment by harendra-kumar** [comment]
@rdnetto thanks for raising the issue. Conduit and Pipes both use the same solution for this, originally introduced by [pipes](https://hackage.haskell.org/package/pipes-4.3.9/docs/Pipes-Lift.html). It sounds reasonable to me to introduce the same solution to streamly, via a Streamly.Lift module. We will need MFunctor and MMonad instances as well to implement it.

I may not be able to get to it in a while, let me know if this is stopping you from using streamly.  In case you want to give it a try please go ahead and raise a PR.

**Comment by harendra-kumar** [comment]
Please see #302. I have added support for running `StateT` and `ReaderT` in parts of stream.
