### ISSUE TITLE
Remove span/spanBy/spanByRolling/break from Data.Fold

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#814]
These should at most be moved to the Parser module and expressed in terms of `groupBy` etc. parsers. Or we can entirely remove them and just keep minima documentation about how to express these in terms of existing parsers.

**Comment by harendra-kumar** [comment]
These are not exposed so we can replace the definitions using parsers. MonadCatch constraint should not be an issue in this case.

**Comment by adithyaov** [comment]
https://github.com/composewell/streamly/pull/890
