### ISSUE TITLE
Network.Socket.writeChunk function hangs  if no. of elements to be written  are less than chunk size.

### ISSUE THREAD

**Issue by rnjtranjan** [composewell/streamly#833]
There should be a mechanism to auto flush the buffer if data is lesser than chunk size.

**Comment by harendra-kumar** [comment]
This is discussed in #456 .

**Comment by harendra-kumar** [comment]
Let's keep this issue for frame based flushing and #456 for timeout based flushing. Quoting rrom #456:

> We can have frame aware buffering combinators such that we can flush the buffer whenever the frame ends. We can have the stream consist of Just a values and use a Nothing to indicate the end of frame. An end of frame indicates a force flush of the buffer. This will give flushing control to the programmer. Even timeout based combinators can be made from such framed combinators. We just need to inject Nothing in the stream at the timeout.

> How much performance overhead will such framing introduce, especially for streams of bytes? It may not be much if it fuses well. Should we have such combinators as default to avoid the pitfalls in the current case?

> Using the current APIs may cause serious inconvenience. So marking this as high priority. However, breaking changes (changing the behavior of the current API) can only go in the next major release. We can have an alternative API before that though.

**Comment by harendra-kumar** [comment]
fixed by #1320
