### ISSUE TITLE
Consider renaming Data.Array.Storable.Foreign to Data.Array.Foreign 

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#854]
The module name Streamly.Data.Array.Storable.Foreign is quite long and this is going to be a very common module to import. Should we shorten this name to Streamly.Data.Array.Foreign?

**Comment by adithyaov** [comment]
I have no issues with this. Does `Foreign` imply `Storable`?

**Comment by harendra-kumar** [comment]
Foreign implies "pinned memory" (Addr#) implemented using `ForeignPtr`, allowing GHC as well as foreign memory allocators. ForeignPtr allows `Storable` as well as `Primitive`. However, only Storable allows both GHC and foreign memory allocators. Primitive works with GHC allocated memory.

By default we can assume `Storable` when we say `Array.Foreign`. If we ever have a Primitive based implementation we can use `Array.Foreign.Primitive`.
