### ISSUE TITLE
fromListM not able to async execution is kinda weird

### ISSUE THREAD

**Issue by eddiemundo** [composewell/streamly#864]
I just noticed that `fromListM` doesn't have the `concurrent` tag underneath it in the documentation so I guess this is known but it's a bit of a UX issue that `fromListM` is different from `fromFoldableM` besides possible performance in the serial case.
```haskell
getResponse :: Int -> IO ()
getResponse key = do
  print ("Begin " <> show key)
  threadDelay 1000000
  print ("End " <> show key)

main :: IO ()
main = do
  [1..5] <&> getResponse & Streamly.fromListM & Streamly.aheadly & Streamly.drain
```
The above gives
```
"Begin 1"
"End 1"
"Begin 2"
"End 2"
"Begin 3"
"End 3"
"Begin 4"
"End 4"
"Begin 5"
"End 5"
```
If I change `fromListM` to `fromFoldableM` it gives
```
"Begin 1"
"Begin 2"
"Begin 3"
"Begin 4"
"Begin 5"
"End 5"
"End 4"
"End 3"
"End 2"
"End 1"
```
which is more what I expect, but I wouldn't known the difference looking at the code alone.

**Comment by harendra-kumar** [comment]
You are right and your expectation is correct. It can in fact be made concurrent easily, we just did not notice it and nobody complained. We will change it in the upcoming release. We just need to change the default definition of fromListM to fromFoldable and write a rewrite rule for serial streams to fall back to the faster non-concurrent version.
