### ISSUE TITLE
Rename some modules

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#873]
Rename:
* Streamly.Internal.Memory.ArrayStream => Streamly.Internal.Data.Array.Stream.Foreign
* Streamly.Memory.Ring => Streamly.Internal.Ring.Foreign

Move to Internal:
*  Streamly.FileSystem.IOVec
* Streamly.FileSystem.FDIO
* Streamly.FileSystem.FD

**Comment by adithyaov** [comment]
We should remove `Streamly.Internal.Memory.ArrayStream`?
