### ISSUE TITLE
Release version compatible with stackage lts 17

### ISSUE THREAD

**Issue by AlistairB** [composewell/streamly#937]
Hi,

Stackage lts 17 has been released which includes `primitive` 0.7.1.0. Due to https://github.com/composewell/streamly/issues/562 `streamly` 0.7.2 requires `primitive` `< 0.7.1`. As such it seems that `streamly` is not included in stackage lts 17.

Can a small streamly release by done that updates to `0.7.2` to work with the latest `primitive`? Otherwise I don't see a way to use streamly with lts 17.

Cheers

**Comment by pranaysashank** [comment]
Thanks for bringing it to our notice, we'll release a new minor version 0.7.3 that is compatible with primitive

**Comment by pranaysashank** [comment]
streamly-0.7.3 has been released on hackage
