### ISSUE TITLE
Test failure on windows (appveyor) with exit code (-1073741675)

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#944]
This tests keeps failing intermittently on Windows (https://ci.appveyor.com/project/harendra-kumar/streamly/builds/37814315):

```
    Prelude.Async:  exited with: ExitFailure (-1073741675)
```

We should either figure out which particular test in this suite is failing and fix/disable that or disable the suite itself and keep it enabled in dev build.

**Comment by adithyaov** [comment]
The following test also has the same exit failure,
https://ci.appveyor.com/project/harendra-kumar/streamly/builds/38059019

**Comment by harendra-kumar** [comment]
Another failure https://ci.appveyor.com/project/harendra-kumar/streamly/builds/38368040:

```
Test suite failure for package streamly-tests-0.0.0
    Data.Array.Foreign:  exited with: ExitFailure (-1073741675)
```

**Comment by adithyaov** [comment]
Here's another one https://ci.appveyor.com/project/harendra-kumar/streamly/builds/38481286
```
Test suite failure for package streamly-tests-0.0.0
    Prelude:  exited with: ExitFailure (-1073741675)
```

**Comment by adithyaov** [comment]
https://ci.appveyor.com/project/harendra-kumar/streamly/builds/38548051
```
Test suite failure for package streamly-tests-0.0.0
    Data.Array.Prim.Pinned:  exited with: ExitFailure (-1073741675)
```

**Comment by harendra-kumar** [comment]
Not seen in a while.
