### ISSUE TITLE
concatPairsWith benchmarks

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#984]
#983 divided nested/expand combinators into two categories, (1) working with concatMapWith with O(n) complexity, (2) working with `concatPairsWith` with O(n x log(n)) complexity. We need benchmarks for the latter to check the performance.
`sortBy` benchmark in Prelude/Serial/Transformation2 is an example of `concatPairsWith mergeBy` benchmark. We can write similar ones for all other combinators from the `Pair Wise` combinators in the `IsStream/Expand` module. These benchmarks should go in Serial/Nested benchmark module along with concatMapWith benchmarks.

**Comment by rnjtranjan** [comment]
You mean below combinators from module Streamly.Internal.Data.Stream.IsStream.Expand:
append ::(IsStream t, Monad m) => t m b -> t m b -> t m b
interleave ::(IsStream t, Monad m) => t m b -> t m b -> t m b
interleaveSuffix ::(IsStream t, Monad m) => t m b -> t m b -> t m b
interleaveInfix ::(IsStream t, Monad m) => t m b -> t m b -> t m b
interleaveMin ::(IsStream t, Monad m) => t m b -> t m b -> t m b
roundrobin ::(IsStream t, Monad m) => t m b -> t m b -> t m b

**Comment by rnjtranjan** [comment]
**Prelude.Serial(cpuTime)**
Benchmark                                                                    default(μs)
---------------------------------------------------------------------------- -----------
Prelude.Serial/o-1-space/concat/concatMapWith (n of 1)                          16915.78
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveInfix                   10223.63
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveSuffix                   9891.84
Prelude.Serial/o-1-space/concat/concatPairWithInterleave                         9513.03
Prelude.Serial/o-1-space/concat/concatPairWithRoundrobin                         9438.22
Prelude.Serial/o-1-space/concat/concatPairWithAppend                             8598.87
Prelude.Serial/o-1-space/concat/concatMapWith (1 of n)                           7944.96
Prelude.Serial/o-1-space/concat/concatMapWithAppend (2 of n/2)                   7924.73
Prelude.Serial/o-1-space/concat-foldable/foldMapM (List)                         6741.75
Prelude.Serial/o-1-space/concat-foldable/foldMapWithM (<>) (List)                6650.82
Prelude.Serial/o-1-space/concat/concatMapWithId (n of 1) (fromFoldable)          6584.64
Prelude.Serial/o-1-space/concat/concatMapId (n of 1) (fromFoldable)              5484.52
Prelude.Serial/o-1-space/concat/concatMapWith (sqrt n of sqrt n)                 3978.99
Prelude.Serial/o-1-space/concat-foldable/foldMapWith (<>) (List)                 3831.37
Prelude.Serial/o-1-space/concat-foldable/S.concatForFoldableWith (<>) (List)     3769.61
Prelude.Serial/o-1-space/concat/concatMapPure (n of 1)                           3336.23
Prelude.Serial/o-1-space/concat/concatMapPure (1 of n)                           2323.50
Prelude.Serial/o-1-space/concat/concatMap (n of 1)                               2321.63
Prelude.Serial/o-1-space/concat/concatMapM (n of 1)                              2258.55
Prelude.Serial/o-1-space/concat-foldable/foldMapWith (<>) (Stream)               2050.20
Prelude.Serial/o-1-space/concat-foldable/S.concatFoldableWith (<>) (List)        1883.98
Prelude.Serial/o-1-space/concat/concatMapM (1 of n)                              1473.23
Prelude.Serial/o-1-space/concat/concatMap (1 of n)                               1464.62
Prelude.Serial/o-1-space/concat/concatMapPure (sqrt n of sqrt n)                 1144.46
Prelude.Serial/o-1-space/concat/concatMapRepl (sqrt n of sqrt n)                  798.61
Prelude.Serial/o-1-space/concat/concatMapM (sqrt n of sqrt n)                     710.27
Prelude.Serial/o-1-space/concat/concatMap (sqrt n of sqrt n)                      704.48
Prelude.Serial/o-1-space/concat/unfoldManyRepl (sqrt n of sqrt n)                 476.24
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveMin                         1.21

**Prelude.Serial(allocated)**
Benchmark                                                                    default(KiB)
---------------------------------------------------------------------------- ------------
Prelude.Serial/o-1-space/concat/concatMapWith (n of 1)                           97595.19
Prelude.Serial/o-1-space/concat/concatMapWithId (n of 1) (fromFoldable)          53845.04
Prelude.Serial/o-1-space/concat/concatMapWith (1 of n)                           48387.76
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveInfix                    39835.71
Prelude.Serial/o-1-space/concat/concatMapWithAppend (2 of n/2)                   39788.88
Prelude.Serial/o-1-space/concat/concatPairWithAppend                             39780.35
Prelude.Serial/o-1-space/concat/concatPairWithRoundrobin                         38997.35
Prelude.Serial/o-1-space/concat/concatPairWithInterleave                         38997.35
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveSuffix                   38997.32
Prelude.Serial/o-1-space/concat-foldable/foldMapM (List)                         29630.97
Prelude.Serial/o-1-space/concat-foldable/foldMapWithM (<>) (List)                29630.97
Prelude.Serial/o-1-space/concat/concatMapWith (sqrt n of sqrt n)                 24456.81
Prelude.Serial/o-1-space/concat-foldable/S.concatForFoldableWith (<>) (List)     24179.92
Prelude.Serial/o-1-space/concat-foldable/foldMapWith (<>) (List)                 24179.92
Prelude.Serial/o-1-space/concat-foldable/foldMapWith (<>) (Stream)               21844.85
Prelude.Serial/o-1-space/concat-foldable/S.concatFoldableWith (<>) (List)        21061.91
Prelude.Serial/o-1-space/concat/concatMapPure (n of 1)                           18711.64
Prelude.Serial/o-1-space/concat/concatMapId (n of 1) (fromFoldable)              17111.53
Prelude.Serial/o-1-space/concat/concatMapPure (1 of n)                           15592.65
Prelude.Serial/o-1-space/concat/concatMapM (n of 1)                               9341.89
Prelude.Serial/o-1-space/concat/concatMap (n of 1)                                9341.89
Prelude.Serial/o-1-space/concat/concatMapPure (sqrt n of sqrt n)                  7843.15
Prelude.Serial/o-1-space/concat/concatMapM (1 of n)                               7786.62
Prelude.Serial/o-1-space/concat/concatMap (1 of n)                                7786.62
Prelude.Serial/o-1-space/concat/concatMapRepl (sqrt n of sqrt n)                  5443.28
Prelude.Serial/o-1-space/concat/concatMapM (sqrt n of sqrt n)                     3914.94
Prelude.Serial/o-1-space/concat/concatMap (sqrt n of sqrt n)                      3914.94
Prelude.Serial/o-1-space/concat/unfoldManyRepl (sqrt n of sqrt n)                 1552.51
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveMin                          3.43

**Prelude.Serial(bytesCopied)**
Benchmark                                                                    default(Bytes)
---------------------------------------------------------------------------- --------------
Prelude.Serial/o-1-space/concat/concatMapWith (n of 1)                             14850.67
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveInfix                       7427.69
Prelude.Serial/o-1-space/concat/concatMapWithId (n of 1) (fromFoldable)             6635.56
Prelude.Serial/o-1-space/concat/concatPairWithInterleave                            6388.57
Prelude.Serial/o-1-space/concat/concatPairWithRoundrobin                            6358.93
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveSuffix                      6306.29
Prelude.Serial/o-1-space/concat/concatMapWith (1 of n)                              6264.89
Prelude.Serial/o-1-space/concat/concatPairWithAppend                                5365.00
Prelude.Serial/o-1-space/concat/concatMapWith (sqrt n of sqrt n)                    5233.45
Prelude.Serial/o-1-space/concat/concatMapWithAppend (2 of n/2)                      4930.00
Prelude.Serial/o-1-space/concat-foldable/foldMapM (List)                            4516.31
Prelude.Serial/o-1-space/concat-foldable/foldMapWithM (<>) (List)                   4516.31
Prelude.Serial/o-1-space/concat-foldable/S.concatForFoldableWith (<>) (List)        3869.60
Prelude.Serial/o-1-space/concat-foldable/foldMapWith (<>) (List)                    3869.60
Prelude.Serial/o-1-space/concat-foldable/S.concatFoldableWith (<>) (List)           2400.00
Prelude.Serial/o-1-space/concat-foldable/foldMapWith (<>) (Stream)                  2091.00
Prelude.Serial/o-1-space/concat/concatMapPure (1 of n)                               844.80
Prelude.Serial/o-1-space/concat/concatMapPure (n of 1)                               723.33
Prelude.Serial/o-1-space/concat/concatMapId (n of 1) (fromFoldable)                  520.80
Prelude.Serial/o-1-space/concat/concatMapPure (sqrt n of sqrt n)                     512.40
Prelude.Serial/o-1-space/concat/concatMapM (1 of n)                                  455.56
Prelude.Serial/o-1-space/concat/concatMap (1 of n)                                   455.56
Prelude.Serial/o-1-space/concat/concatMapRepl (sqrt n of sqrt n)                     396.52
Prelude.Serial/o-1-space/concat/concatMapM (n of 1)                                  363.73
Prelude.Serial/o-1-space/concat/concatMap (n of 1)                                   363.73
Prelude.Serial/o-1-space/concat/concatMapM (sqrt n of sqrt n)                        301.44
Prelude.Serial/o-1-space/concat/concatMap (sqrt n of sqrt n)                         301.44
Prelude.Serial/o-1-space/concat/unfoldManyRepl (sqrt n of sqrt n)                    156.80
Prelude.Serial/o-1-space/concat/concatPairWithInterleaveMin                            1.97

**Comment by harendra-kumar** [comment]
fixed by #1001
